### ISSUE TITLE
Reject reason : code:-1 data: message:duplicate share

### ISSUE THREAD

**Issue by Raspimann** [oliverw/miningcore#1043]
I used the latest version of miningcore 64.0.1.0 with geth 1.12 stable.

i see somethimes these in den mining window:

...
14:58:19 miner Reject reason : code:-1 data: message:duplicate share
14:58:19 miner **Rejected   25 ms. x.x.x.x:4073
...

what this means?

do geth/miningcore/miner software work all fine?

do miningcore or geth rejected the share?

**Comment by oliverw** [comment]
This is nothing to be concerned about Happens from time to time. If it happens for the majority of submitted shares, its a miner using outdated mining software or he's trying to cheat.
