### ISSUE TITLE
always tell me Waiting for daemons to come online ... 

### ISSUE THREAD

**Issue by James1847** [oliverw/miningcore#1048]
![image](https://user-images.githubusercontent.com/29943599/147259313-b6113447-65f9-4be9-8644-e92a87bb922c.png)

why it's always tell me Waiting for daemons to come online ... 
should I wait my geth to sync data complete?

**Comment by BitWizJason** [comment]
@James1847 Yes, you have to wait for Geth to finish syncing before you can connect and use it via the mining pool. The sync can take a couple of days depending on your hardware and sync options.

**Comment by oliverw** [comment]
> @James1847 Yes, you have to wait for Geth to finish syncing before you can connect and use it via the mining pool. The sync can take a couple of days depending on your hardware and sync options.

_Waiting for daemons to come online ..._ means that the pool is unable to communicate with the daemon (geth) at all.

**Comment by XIII39** [comment]
As I recall, when I was having this issue it was because I didn't have the http.api and ws.api launched in geth. No daemons to connect to if there is nothing to allow a connection. 

$ geth --http --http.port=8545 --http.api=eth,net,web3,miner --ws --ws.port=8546 --ws.api=eth,net,web3,miner
