### ISSUE TITLE
Waiting for daemons to connect to peers

### ISSUE THREAD

**Issue by James1847** [oliverw/miningcore#1055]
when geth is ready to work and after I restarted the minigcore, it always shows me below:
![image](https://user-images.githubusercontent.com/29943599/147675751-0bdeaaaf-edb2-43bd-82bc-5941376afcac.png)
how does my peers able to connect to minigcore, and the listenaddress is my public address and the port is 8008 for the eth1 section in my config.json, does anyone know how to fix it?

**Comment by XIII39** [comment]
I believe you have to enable the http.api and ws.api when you launch geth.
I use `--http --http.port=8545 --http.api=eth,net,web3,miner --ws --ws.port=8546 --ws.api=eth,net,web3,miner`

**Comment by James1847** [comment]
> I believe you have to enable the http.api and ws.api when you launch geth. I use `--http --http.port=8545 --http.api=eth,net,web3,miner --ws --ws.port=8546 --ws.api=eth,net,web3,miner`
> 
> If you're using port 8008 then change the 8545 for the http.api to 8008, you can also try to set the listenaddress to '*' or '127.0.0.1' in your config.json

Yes, I had fixed it, I'm so pleased that u can help me, thank you
