### ISSUE TITLE
Issue with latest build and build output appears incorrect

### ISSUE THREAD

**Issue by senatorbingham** [oliverw/miningcore#1060]
**Describe the bug**

**To Reproduce**
1. Using instructions from Readme.MD simply run 'git clone https://github.com/oliverw/miningcore'
2. Build 'dotnet publish -c Release --framework net6.0  -o ..\..\build'
3. Once build completes check output directory '~/miningcore/src/Miningcore/....build' instead of '~/miningcore/build'
4. Attempt to run from output directory noted above
5. See error 'Configuration file error: Value "integrated" is not defined in enum. Path 'banning.manager', line 12, position 31'

**Expected behavior**
Except build directory to be the same as prior builds, expect MC to launch using a prior known good config

**Comment by oliverw** [comment]
That was an unfortunate breaking change introduced by the release. It's now documented here: 

https://github.com/oliverw/miningcore/releases/tag/v65

**Comment by warren-ru** [comment]
I'm facing the same bug in the 67 version.

**Comment by oliverw** [comment]
> I'm facing the same bug in the 67 version.

The required change is of course required for all subsequent releases. after https://github.com/oliverw/miningcore/releases/tag/v66.
