### ISSUE TITLE
functions in index expression must be marked IMMUTABLE

### ISSUE THREAD

**Issue by James1847** [oliverw/miningcore#1061]
psql:createdb.sql:123: ERROR:  functions in index expression must be marked IMMUTABLE
psql:createdb.sql:124: ERROR:  functions in index expression must be marked IMMUTABLE

the corresponse sql lines in createdb.sql are:

CREATE INDEX IDX_MINERSTATS_POOL_MINER_CREATED_HOUR on minerstats(poolid, miner, date_trunc('hour',created));
CREATE INDEX IDX_MINERSTATS_POOL_MINER_CREATED_DAY on minerstats(poolid, miner, date_trunc('day',created));

what's going no? I'm using psql (12.9 (Ubuntu 12.9-0ubuntu0.20.04.1))

**Comment by BeAristobule** [comment]
Same problem on ubuntu 21.04

**Comment by James1847** [comment]
> Same problem on ubuntu 21.04

this is ubuntu 20.04

**Comment by oliverw** [comment]
Fixed by f5a7f1a

https://github.com/oliverw/miningcore/releases/tag/v66
