### ISSUE TITLE
 [eth1] System.Exception: eth_sendTransaction returned error: unknown account code -32000

### ISSUE THREAD

**Issue by James1847** [oliverw/miningcore#1076]
![image](https://user-images.githubusercontent.com/29943599/148652968-26cc9423-5936-438b-adc3-4e7afd0cb5f7.png)
![image](https://user-images.githubusercontent.com/29943599/148653001-8c43873d-c990-4036-a078-92542d8e6850.png)

how can I solve this problem, I guess the problem is in the config.json -> "paymentProcessing" block, I didn't set the payment private_key, Can u tell me how to set my private_key into the config.json, then miningcore can use PPLNS to send ETH rewards to the miner address? 
If I can't set private key in config.json, Should I must create a local eth account by using "geth account new" command, and then when I start geth, I also has to set the password into the geth command? Finally, how to set this account password in mingingcore config.json ?

**Comment by seperatis** [comment]
https://github.com/oliverw/miningcore/wiki/Coin-Daemon-&-Wallet-RPC#ethereum

**Comment by James1847** [comment]
> https://github.com/oliverw/miningcore/wiki/Coin-Daemon-&-Wallet-RPC#ethereum

after I use the --unlock and --insecure-unlock option to run my geth, still get the same error

**Comment by James1847** [comment]
> https://github.com/oliverw/miningcore/wiki/Coin-Daemon-&-Wallet-RPC#ethereum

After I restart the geth with the right option command(geth unlock and unlock insecure option), I can mine the block and mingcore tell me that I can also send the rewards the miners, I started my geth in Ethereum Rospten Testnet...., the details shows below, this is mingcore shows me the content:
![image](https://user-images.githubusercontent.com/29943599/148666713-c1452056-edcc-4038-a4d7-3c16df389570.png)
below is geth shows me the content:
![image](https://user-images.githubusercontent.com/29943599/148666767-30736ae7-8be6-40f9-bfb9-56847937a579.png)

But when I search the transaction id in https://ropsten.etherscan.io/tx/0xfd6f46d2f4e4ef5e91aa49c3540fdc2dbc63413e227767b7afde7fa284c072f5
I found nothing about the transfer details, The ETH is still in my main wallet address, what's going on?

**Comment by oliverw** [comment]
> > https://github.com/oliverw/miningcore/wiki/Coin-Daemon-&-Wallet-RPC#ethereum
> 
> After I restart the geth with the right option command(geth unlock and unlock insecure option), I can mine the block and mingcore tell me that I can also send the rewards the miners, I started my geth in Ethereum Rospten Testnet...., the details shows below, this is mingcore shows me the content: ![image](https://user-images.githubusercontent.com/29943599/148666713-c1452056-edcc-4038-a4d7-3c16df389570.png) below is geth shows me the content: ![image](https://user-images.githubusercontent.com/29943599/148666767-30736ae7-8be6-40f9-bfb9-56847937a579.png)
> 
> But when I search the transaction id in https://ropsten.etherscan.io/tx/0xfd6f46d2f4e4ef5e91aa49c3540fdc2dbc63413e227767b7afde7fa284c072f5 I found nothing about the transfer details, The ETH is still in my main wallet address, what's going on?
> 
> And when I use geth attach to finds something in geth, I tried to use eth.pendingTransactions, the content shows blow: ![image](https://user-images.githubusercontent.com/29943599/148667154-f2e5d9bd-170b-4dc0-8f24-f03c22602c0d.png) I guess the problem is I didn't set gas price for my transaction, so where can I set gas_price in miningcore or geth?

We currently don't have support for this in MC.
