### ISSUE TITLE
Zcash Exception

### ISSUE THREAD

**Issue by konstiantyn** [oliverw/miningcore#1086]
![Zcash bug](https://user-images.githubusercontent.com/33037366/148917782-2985b3c8-39bf-4ec0-bdee-b5c5c0a071c1.png)

**Comment by oliverw** [comment]
Unfortunately I have no idea why this happens. Could you perhaps file an issue at https://github.com/MetacoSA/NBitcoin?

**Comment by konstiantyn** [comment]
I downgrade nbitcoin verison to 5.0.83, nbitcoin.altcoin version to 2.0.34
It works.

**Comment by oliverw** [comment]
> 

PR please? :)

**Comment by konstiantyn** [comment]
I'll send pull request.
