### ISSUE TITLE
integrated error to run config.json

### ISSUE THREAD

**Issue by alirezababae** [oliverw/miningcore#1099]
![2022-01-14-233139_1366x768_scrot](https://user-images.githubusercontent.com/36876501/149578680-a0a6a628-a161-4448-872c-4aa580bf0484.png)

**Comment by XIII39** [comment]
In your config.json file change line 11 from;
"manager": "integrated", to 
"manager": "Integrated",

**Comment by alirezababae** [comment]
> In your config.json file change line 11 from; `"manager": "integrated"` to `"manager": "Integrated"`
> 
> The change happened in Release 66 https://github.com/oliverw/miningcore/releases/tag/v66
