### ISSUE TITLE
waiting for daemons to come online

### ISSUE THREAD

**Issue by alirezababae** [oliverw/miningcore#1104]
What is the message waiting for the demons to go online?

![2022-01-15-115917_1366x768_scrot](https://user-images.githubusercontent.com/36876501/149616338-f265b60c-f870-4ddd-839d-e378b2b765e9.png)

**Comment by XIII39** [comment]
Either your node is still syncing or Miningcore isn't receiving data from the node. If you're fully synced, check that the http and ws ports are set in your config.json file under the "daemons" section. Also well as make sure your node is sending the notify data on those ports.

I'm not 100% sure with BTC but this is how I did it with ETH
https://github.com/oliverw/miningcore/issues/1055

Hopefully this helps

**Comment by HarryTBB** [comment]
I'm new to ETH and Miningcore and having the same issue. Not sure what is meant by the node is still syncing... Does it mean Miningcore is trying to sync to an Ethereum node? How long should I wait for the daemons to come online?
