### ISSUE TITLE
connect miner

### ISSUE THREAD

**Issue by alirezababae** [oliverw/miningcore#1105]
How do I connect a miner? Does it  support pool stratum?

**Comment by XIII39** [comment]
Stratum V1 & V2 are supported. Just direct your miner to the IP address and port you've configured in the config.json file

On my local network I would use `stratum2+tcp://192.168.1.225:3030` or `stratum+tcp://192.168.0.225:3030` depending on the miner. Obviously anyone connecting from outside of your network would connect to your public IP or domain you setup in your DNS. Don't forget to open the appropriate ports on your firewall and/or configure any port forwarding on your router/switch

**Comment by alirezababae** [comment]
Thanks
I use a virtual machine(virtualbox), does this cause a problem?

**Comment by XIII39** [comment]
That's out of my scope of experience. Perhaps there is someone else who has more experience with VM who can chime in here.

**Comment by oliverw** [comment]
> Thanks I use a virtual machine(virtualbox), does this cause a problem?

No it does not. How many miners are you planning to support with your pool?

**Comment by alirezababae** [comment]
> 

I'm going to connect to the pool in the virtual machine via ASIC

**Comment by oliverw** [comment]
> yes , I'm going to connect to the pool in the virtual machine via ASIC

That was not my question.
