### ISSUE TITLE
Error "Value "integrated" is not defined in enum. Path 'banning.manager'"

### ISSUE THREAD

**Issue by warren-ru** [oliverw/miningcore#1115]
Describe the bug

To Reproduce

    Using instructions from Readme.MD simply run 'git clone https://github.com/oliverw/miningcore'
    Build 'dotnet publish -c Release --framework net6.0 -o ....\build'
    Once build completes check output directory '/miningcore/src/Miningcore/....build' instead of '/miningcore/build'
    Attempt to run from output directory noted above
    See error 'Configuration file error: Value "integrated" is not defined in enum. Path 'banning.manager', line 12, position 31'

Expected behavior
Except build directory to be the same as prior builds, expect MC to launch using a prior known good config

**Comment by warren-ru** [comment]
#1060 bug remains

**Comment by oliverw** [comment]
> #1060 bug remains in 67.0.1

It's not a bug. It is clearly described as breaking change in the release notes: https://github.com/oliverw/miningcore/releases/tag/v66

**Comment by warren-ru** [comment]
Ok. In #1060 you mentioned it in release 65 notes.
So I didn't find anything.
Now it's clear.

**Comment by oliverw** [comment]
> Ok. In #1060 you mentioned it in release 65 notes. So I didn't find anything. Now it's clear.

Sorry for the confusion.
