### ISSUE TITLE
Cgminer Error 

### ISSUE THREAD

**Issue by 1984winstonsmith** [oliverw/miningcore#1123]
What is the reason for this error in Cgminer? I attached the images and config file

Cgminer  

![Screenshot_2022-01-19_10-26-24](https://user-images.githubusercontent.com/98042818/150171516-3b8151e9-8e5a-49fb-8865-2439aad3eb89.png)

Bitcoind 

![Screenshot_2022-01-19_08-10-52](https://user-images.githubusercontent.com/98042818/150171602-78bfc487-7dd1-4216-b25a-dadb2a18c978.png)

Pool Status 

![Screenshot_2022-01-19_08-56-49](https://user-images.githubusercontent.com/98042818/150171755-6f79880f-daf6-4639-8011-b3e616651224.png)

Config File

{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "Integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": true,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "test1234",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
      "id": "btc1",
      "enabled": true,
      "coin": "bitcoin",
      "address": "LNDA11u4HWzbJaBGiHDvs6SmA8M6avB3wH",
      "rewardRecipients": [
        {
          "address": "LUWYwkz6DQLVeqJqHRtGjNhWUxBvBmE3SX",
          "percentage": 1.0
        }
      ],
      "blockRefreshInterval": 500,
      "jobRebroadcastTimeout": 10,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "3042": {
          "listenAddress": "127.0.0.1",
          "difficulty": 1024,
          "name": "ASIC Mining",
          "varDiff": {
            "minDiff": 512,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        }
      },
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 18332,
          "user": "user",
          "password": "pass"
    }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }]
}

**Comment by konstiantyn** [comment]
This is not a error. You will need to wait for the Bitcoin Core sync to complete.

**Comment by 1984winstonsmith** [comment]
> This is not a error. You will need to wait for the Bitcoin Core sync to complete.

Must ; daemon has download  ; Be 100%?

**Comment by 1984winstonsmith** [comment]
i useing bitcoin core 0.20.1

**Comment by 1984winstonsmith** [comment]
Thanks
