### ISSUE TITLE
Accepted rate low in ASIC

### ISSUE THREAD

**Issue by konstiantyn** [oliverw/miningcore#1126]
![image](https://user-images.githubusercontent.com/33037366/150380084-0131bd28-94ba-416e-8b08-6e5d99633a90.png)

many stale share, low difficulty share, duplicate share in Ethereum pool.

**Comment by konstiantyn** [comment]
![image](https://user-images.githubusercontent.com/33037366/150385124-ae9873ad-8c1c-4172-8845-ef231fb17092.png)

**Comment by oliverw** [comment]
I've asked you several times in the comments for your PR why you think your PR fixes the problem. You never gave an explanation but instead just closed the PR without comment.

**Comment by konstiantyn** [comment]
1.That sends the current difficulty again. It does not set a new one.
2.It sends a notification after a share submission which is not exactly whats in the spec
3.It sends a v2 notifications to v1 clients

I think it's all right. So I closed my PR.

**Comment by oliverw** [comment]
Please retest with v68

**Comment by konstiantyn** [comment]
I think It works well. Thanks for your working

**Comment by seperatis** [comment]
@konstiantyn

Is this resolved?
