### ISSUE TITLE
FPPS

### ISSUE THREAD

**Issue by 1984winstonsmith** [oliverw/miningcore#1128]
Why can't I use "payoutScheme": "FPPS",
use?

**Comment by arubinofaux** [comment]
FPPS is not supported

https://github.com/oliverw/miningcore/blob/f6ceed6c8a6cacd462adc0bf9fc4beca07034cd5/src/Miningcore/Configuration/ClusterConfig.cs#L483

**Comment by oliverw** [comment]
> FPPS is not supported
> 
> https://github.com/oliverw/miningcore/blob/f6ceed6c8a6cacd462adc0bf9fc4beca07034cd5/src/Miningcore/Configuration/ClusterConfig.cs#L483

Only the first three are actually supported.

**Comment by 1984winstonsmith** [comment]
> > FPPS is not supported
> > https://github.com/oliverw/miningcore/blob/f6ceed6c8a6cacd462adc0bf9fc4beca07034cd5/src/Miningcore/Configuration/ClusterConfig.cs#L483
> 
> Only the first three are actually supported.


Why not add PPS?

 What should I do if I want to use PPS?

**Comment by oliverw** [comment]
> > > FPPS is not supported
> > > https://github.com/oliverw/miningcore/blob/f6ceed6c8a6cacd462adc0bf9fc4beca07034cd5/src/Miningcore/Configuration/ClusterConfig.cs#L483
> > 
> > 
> > Only the first three are actually supported.
> 
> Why not add F/PPS?
> 
> What should I do if I want to use F/PPS?

Code it and submit a PR?
