### ISSUE TITLE
Ethereum Stratum v1 workername 

### ISSUE THREAD

**Issue by coolman888** [oliverw/miningcore#1140]
Hi,
The v1 can not get workname from mining software  with `<wallet_address>.<workername>,` but works with parame `-w <workername>`.

Can you get both work with `<wallet_address>.<workername>`  and `-w <workername>`  ?

Thank you very much!

**Comment by oliverw** [comment]
We definitely support both:

https://github.com/oliverw/miningcore/blob/master/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs#L203

**Comment by coolman888** [comment]
![1](https://user-images.githubusercontent.com/95366323/151346912-3be903c0-c93e-43b4-9c62-dd9c7fdd5312.png)

It seems doesn't work.

The bule is using `t-rex.exe -a ethash -o stratum+ssl://xxx.xxx.xxx:8888 -u wallet_address -p x -w coolman008`

The red one is using `teamredminer.exe  -a ethash -o stratum+ssl://xxx.xxx.xxx:8888 -u wallet_address.coolman006 -p x`

Please check, Thanks again.

**Comment by oliverw** [comment]
Weird, I'll give it a second look.

**Comment by coolman888** [comment]
> Weird, I'll give it a second look.

Dear oilverw, Any news on it?

**Comment by oliverw** [comment]
> > Weird, I'll give it a second look.
> 
> Dear oilverw, Any news on it?

Not, yet. Currently busy with other stuff.

**Comment by xmrstickers** [comment]
Can confirm this is happening in Lolminer as well. T-rex "-w" flag passes worker correctly, however, Lolminer will leave the worker unnammed through both **wallet.worker** nomenclature or using the --worker flag in extra args.

**Comment by kr1z1s** [comment]
Workername is not displayed with TeamRed miner last version. Tested on ETHW coin.
