### ISSUE TITLE
Low diff shares  bug has been not fixed for Stratum version 2.

### ISSUE THREAD

**Issue by kr1z1s** [oliverw/miningcore#1147]
https://github.com/oliverw/miningcore/issues/1062
This bug has been fixed for Stratum version 1. 
However, for stratum version 2, the error persists.
It does not occur immediately. 
Here is a screenshot after 79 shares with t-rex 0.24.8

Stratum V2
![stratum2](https://user-images.githubusercontent.com/5347595/151747283-b3ea718a-6ee1-4ff4-9c12-c433d4078d74.jpg)

Stratum V1
![stratum1](https://user-images.githubusercontent.com/5347595/151747483-3af337a1-ced1-4a15-881b-fc7ea06d5b90.jpg)

_Originally posted by @kr1z1s in https://github.com/oliverw/miningcore/issues/1062#issuecomment-1025414726_

**Comment by kr1z1s** [comment]
> Status?

I'll check it out

**Comment by BznGit** [comment]
![V2](https://user-images.githubusercontent.com/73360255/191099793-97887832-ceb2-4e01-be86-21a81af5c43e.png)
t-rex miner whith 79 shares

**Comment by BznGit** [comment]
stratun v2

**Comment by BznGit** [comment]
![v1](https://user-images.githubusercontent.com/73360255/191106818-852a07a4-5908-4c87-ae46-922a9e2dca3b.png)
It's stratum v1 t-rex miner 79 shares

**Comment by oliverw** [comment]
Looks good to me?

**Comment by BznGit** [comment]
I think the same

**Comment by oliverw** [comment]
Is that with the updated t-rex?

**Comment by BznGit** [comment]
Yes, it a 0.26.4 version

**Comment by oliverw** [comment]
Ok, closing this for now then. Thanks for the update. 👍

**Comment by BznGit** [comment]
Ok
