### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by rmapelli** [oliverw/miningcore#1169]
Hi everyone, everything fine? So I'm sorry but I need your help, I'm testing a pool with RTM (raptoreum), but every time I run the pool when the miner connects it shows this error, what do you think it could be? I've exhausted my possibilities here.

Below is the pool's config.

 "ports": {
          "4073": {
            "diff" : 0.1,
            "name": "Bem Vindo ao Pool Doge",
            "listenAddress": "*",
            "difficulty": 0.1,
            "varDiff": {
              "minDiff": 0.1,
              "maxDiff": 7000,
              "targetTime": 15,
              "retargetTime": 60,
              "variancePercent": 30,
              "maxDelta": 0.5,
              "maxJump": 25,
              "max_ttf": 40000
            }
          }
        },
        "daemons": [
          {
            "host": "192.168.1.64",
            "port": 9998,

![image](https://user-images.githubusercontent.com/59071055/154743431-b04afd79-a436-425d-9579-fc903644635b.png)

I would be grateful for your help ^^

**Comment by Jimmy062006** [comment]
Replace the following lines in the file

[src/Native/libcryptonight/Makefile]

![image](https://user-images.githubusercontent.com/4639349/157093543-33a233cb-49ff-43b5-a200-ccbf17ae7830.png)

**Comment by oliverw** [comment]
Fixed by 0313f6c34e9a0fbe4a39b2dce832c7b22c43edce

**Comment by rmapelli** [comment]
Hello, thank you very much, it worked, sorry for the delay I ended up having some problems. I went to test with the wildrig-multi miner and for some reason it sent the invalid instruction, I ended up giving up on it.
I just wanted some more help or some direction I'm quite a noob and it's my first time trying to be a mining server you know why this error happens, I looked in other answers but I didn't understand very well. Thanks for the help as always, stay safe. Sorry for the English, I use google translator. ^^

![image](https://user-images.githubusercontent.com/59071055/168595652-a2cd740b-1444-4dcf-b10c-ad716512ab01.png)

**Comment by rmapelli** [comment]
@oliverw 

Estou fazendo algo errado?



![image](https://user-images.githubusercontent.com/59071055/169557580-6407fc1c-dd8a-4dc3-940c-8c7f407a9302.png)


Segue minhas configs:


{

"logging": {
        "level": "trace",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "apiLogFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "Integrated",
        "banOnJunkReceive": false,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "pool support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "re@1928.",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 10,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "api": {
        "enabled": true,
        "listenAddress": "*",
        "port": 4000,
        "metricsIpWhitelist": [],
        "rateLimiting": {
            "disabled": true,
            "rules": [
                {
                    "Endpoint": "*",
                    "Period": "1s",
                    "Limit": 5
                }
            ],
            "ipWhitelist": [
                ""
            ]
        }
    },
    "clusterName": "eu1",
    "pools": [
      {
        "id": "Raptoreum",
        "enabled": true,
        "coin": "raptoreum",
        "address": "RYWDe9DXuSZRxt9SZ72wB6ctvRGagCRUdj",
        "HasLegacyDaemon": false,
        "hasBrokenSendMany": false,
        "rewardRecipients": [
          {
            "address": "R9w4AopJgtnWWmLK2pyxDRu5ArZ5h4Thme",
            "percentage": 0.01
          }
        ],
        "blockRefreshInterval": 333,
        "clientConnectionTimeout": 600,
        "banning": {
          "enabled": true,
          "time": 600,
          "invalidPercent": 50,
          "checkThreshold": 50
        },
        "ports": {
          "4073": {
            "name": "Bem Vindo ao Pool Raptoreum",
            "listenAddress": "*",
            "difficulty": 128,
            "varDiff": {
              "minDiff": 0.05,
              "maxDiff": null,
              "targetTime": 15,
              "retargetTime": 90,
              "variancePercent": 30
            }
          }
        },
        "chainTypeOverride": "Raptoreum",
        "dagDir": "<Your directory for the dag file>",
        "daemons": [
          {
            "host": "192.168.1.104",
            "port": 10226,
            "user": "raptoreum",
            "password": "xinfox"
          }
        ],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 0.5,
            "payoutScheme": "PPLNS",
            "payoutSchemeConfig": {
                "factor": 0.5
            },
            "gas": 21000,
            "maxFeePerGas": 50000000000,
            "keepUncles": false,
            "keepTransactionFees": false
        }
      }
    ]
}

**Comment by rmapelli** [comment]
![image](https://user-images.githubusercontent.com/59071055/169591105-7f07b7fe-1e98-4544-bbc0-cb0f9b1ca5ab.png)
