### ISSUE TITLE
Second Daemon is not used by stratum

### ISSUE THREAD

**Issue by ei8ht187** [oliverw/miningcore#1187]
**Describe the bug**
We have two fullnodes per coin configured. When I shut down the primary fullnode Miningcore stops working. It does not switch to the second fullnode. We have encountered this behaviour with ERGO.

**To Reproduce**
Set up two ERGO Fullnodes, configure them as deamons in MC Stratum. Shut the first daemon from the configuration down.

**Expected behavior**
Miningcore should automatically switch over to second daemon.

**Comment by oliverw** [comment]
Support for multiple daemons has been dropped ages ago. The only reason for daemons being  an array in the config is that there are coins which require multiple daemon endpoints for different purposes like Monero's wallet daemon to name one example.
