### ISSUE TITLE
GPDR compatible logging

### ISSUE THREAD

**Issue by oliverw** [oliverw/miningcore#1205]
### Discussed in https://github.com/oliverw/miningcore/discussions/1200

<div type='discussions-op-text'>

<sup>Originally posted by **ei8ht187** March  7, 2022</sup>
At the moment, as soon as you activate logging with setting info or debug, the ip addresses are all visible in full. It should give a GPDR option to censor the output of the IP adresses, either set them to 0.0.0.0 or something like 192.000.000.192. 
Of course this has to be adjusted after the banning manager function.

With this, you still have some information and can troubleshoot, without having the full IP information saved in your logs. </div>

**Comment by jon4hz** [comment]
@oliverw I think you can close this now :)
