### ISSUE TITLE
Error when using Team Red Miner on Ergo Pool

### ISSUE THREAD

**Issue by MiningCryptoLive** [oliverw/miningcore#1218]
### Discussed in https://github.com/oliverw/miningcore/discussions/1217

<div type='discussions-op-text'>

<sup>Originally posted by **MiningCryptoLive** March 29, 2022</sup>
I get this error when trying to use Team Red Miner on  my Ergo Pool. Any help would be appreciated.

![Screenshot 2022-03-29 070403](https://user-images.githubusercontent.com/1049926/160598232-7f0f5f67-a6c9-4b89-8e4f-d553393e4c2e.png)
</div>

**Comment by vinnielima** [comment]
We are experiencing the same thing, just moved to the latest v69 release and many of our users are experiencing this error.

**Comment by kr1z1s** [comment]
> ### Discussed in #1217
> Originally posted by **MiningCryptoLive** March 29, 2022 I get this error when trying to use Team Red Miner on my Ergo Pool. Any help would be appreciated.
> 
> ![Screenshot 2022-03-29 070403](https://user-images.githubusercontent.com/1049926/160598232-7f0f5f67-a6c9-4b89-8e4f-d553393e4c2e.png)

Same error with Team Red and Vertcoin pool.
