### ISSUE TITLE
Reported Hashrate

### ISSUE THREAD

**Issue by masksnytko** [oliverw/miningcore#1219]
Hello team.
I want to get data from api about Reported Hashrate from miner.
Could you provide this in new release?

Also I can see information in console
"Connection json error: Unexpected character encountered while parsing value: G. Path '', line 0, position 0."
Maybe this is related to this.

Thanks for the support!

**Comment by oliverw** [comment]
> Hello team. I want to get data from api about Reported Hashrate from miner. Could you provide this in new release?

Are you referring to `eth_submitHashrate` ?

**Comment by masksnytko** [comment]
> > Hello team. I want to get data from api about Reported Hashrate from miner. Could you provide this in new release?
> 
> Are you referring to `eth_submitHashrate` ?

Yes. I think many miners send this information for coins.

**Comment by oliverw** [comment]
Miningcore currently ignores this message and thus does not store that info anywhere.

**Comment by ei8ht187** [comment]
I am interested in the reported hashrate too. It is a good way for miners to check against the calculated values from the pool.
