### ISSUE TITLE
pool starting error

### ISSUE THREAD

**Issue by goodthebest** [oliverw/miningcore#1220]
I'm getting this error when starting Ethereum pool, any clue?
![image](https://user-images.githubusercontent.com/1715740/161081826-a8b8ac8c-0b0c-4b26-abd6-cdd86b8bb678.png)

**Comment by goodthebest** [comment]
{
    "$schema": "https://raw.githubusercontent.com/oliverw/miningcore/master/src/Miningcore/config.schema.json",
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "apiLogFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "Integrated",
        "banOnJunkReceive": false,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "pool support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "xxx",
            "database": "miningcore"

        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 100,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "api": {
        "enabled": true,
        "listenAddress": "*",
        "port": 4000,
        "metricsIpWhitelist": [],
        "rateLimiting": {
            "disabled": true,
            "rules": [
                {
                    "Endpoint": "*",
                    "Period": "1s",
                    "Limit": 5
                }
            ],
            "ipWhitelist": [
                ""
            ]
        }
    },
    "clusterName": "eu1",
    "pools": [
      {
        "id": "eth1",
        "enabled": true,
        "coin": "ethereum",
        "address": "0x67e21987c52ae87aaf28eb62acee2d8808db6b61",
        "rewardRecipients": [
          {
            "type": "op",
            "address": "0xF8470A06f46Ab6340f94d8E153cB9c548744546E",
            "percentage": 0.0
          }
        ],
        "blockRefreshInterval": 120,
        "clientConnectionTimeout": 600,
        "banning": {
          "enabled": true,
          "time": 600,
          "invalidPercent": 50,
          "checkThreshold": 50
        },
        "ports": {
          "4073": {
            "name": "GPU-SMALL",
            "listenAddress": "*",
            "difficulty": 0.1,
            "varDiff": {
              "minDiff": 0.1,
              "maxDiff": null,
              "targetTime": 15,
              "retargetTime": 90,
              "variancePercent": 30
            }
          }
        },
        "chainTypeOverride": "Ethereum",
        "dagDir": "",
        "daemons": [
          {
            "host": "127.0.0.1",
            "port": 8545,
            "user": "",
            "password": ""
          }
        ],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 1,
            "payoutScheme": "PPLNS",
            "payoutSchemeConfig": {
                "factor": 0.5
            },
            "gas": 21000,
            "maxFeePerGas": 50000000000,
            "keepUncles": false,
            "keepTransactionFees": false
        }
      }
    ]
}

**Comment by iamraisanjeev** [comment]
same error, im banging head against the wall for 2 days,

**Comment by oliverw** [comment]
I was now able to reproduce the problem.

**Comment by iamraisanjeev** [comment]
is it something we done wrong??

**Comment by oliverw** [comment]
No.

**Comment by iamraisanjeev** [comment]
waiting for update sir, u got discord btw?

**Comment by oliverw** [comment]
The problem is most likely that the postgres database user in your configuration does not have sufficient permission on the database.

**Comment by babelfish2001** [comment]
How can we make sure the database user has the appropriate permissions?
