### ISSUE TITLE
Strange NetworkHashrate for ERGO

### ISSUE THREAD

**Issue by ei8ht187** [oliverw/miningcore#1231]
ERGO returns a strange network hashrate. According to Miningcore, the Network Hashrate is 48000EH/s. The official ERGO Explorer reports 15.5TH/s. 

![Bildschirmfoto vom 2022-04-05 21-02-13](https://user-images.githubusercontent.com/72598876/161831364-826a283f-4126-40e5-8eac-374661b9076f.png)
Is this a missconfiguration on my side or an error within Miningcore?

**Comment by MiningCryptoLive** [comment]
> ERGO returns a strange network hashrate. According to Miningcore, the Network Hashrate is 48000EH/s. The official ERGO Explorer reports 15.5TH/s.
> 
> ![Bildschirmfoto vom 2022-04-05 21-02-13](https://user-images.githubusercontent.com/72598876/161831364-826a283f-4126-40e5-8eac-374661b9076f.png) Is this a missconfiguration on my side or an error within Miningcore

Must be something misconfigured. I have ergo pool running miningcore and the network hashrate shows correctly.

**Comment by ei8ht187** [comment]
Problem reappeared with v72 (maybe also v71, can't recall correctly). Please also see my comment here: https://github.com/oliverw/miningcore/commit/0a1029e922c033955b1a2db82cf7fc43b19aa157

We are using your UI and haven't fixed anything within the ERGO stuff.

**Comment by MiningCryptoLive** [comment]
I am using v72 and the hashrate is being displayed correctly

**Comment by MiningCryptoLive** [comment]
![Screenshot_20220815-122438.png](https://user-images.githubusercontent.com/1049926/184675022-640d20d2-c0ab-4fcb-b698-b303ce5b8a5f.png)

**Comment by oliverw** [comment]
> Problem reappeared with v72 (maybe also v71, can't recall correctly). Please also see my comment here: [0a1029e](https://github.com/oliverw/miningcore/commit/0a1029e922c033955b1a2db82cf7fc43b19aa157)
> 
> We are using your UI and haven't fixed anything within the ERGO stuff.

https://github.com/oliverw/miningcore/commit/0a1029e922c033955b1a2db82cf7fc43b19aa157#commitcomment-81235236

**Comment by MiningCryptoLive** [comment]
> Problem reappeared with v72 (maybe also v71, can't recall correctly). Please also see my comment here: https://github.com/oliverw/miningcore/commit/0a1029e922c033955b1a2db82cf7fc43b19aa157
> 
> We are using your UI and haven't fixed anything within the ERGO stuff. 

Maybe try git pull to make sure you have all updates and rebuild

**Comment by ei8ht187** [comment]
> > Problem reappeared with v72 (maybe also v71, can't recall correctly). Please also see my comment here: [0a1029e](https://github.com/oliverw/miningcore/commit/0a1029e922c033955b1a2db82cf7fc43b19aa157)
> > We are using your UI and haven't fixed anything within the ERGO stuff.
> 
> [0a1029e#commitcomment-81235236](https://github.com/oliverw/miningcore/commit/0a1029e922c033955b1a2db82cf7fc43b19aa157#commitcomment-81235236)

Thanks, this did the trick. Problem was in the UI
