### ISSUE TITLE
Connection Accepting and Closing

### ISSUE THREAD

**Issue by mxride** [oliverw/miningcore#1234]
After messing around for a few days I have finally gotten my miner connected to my MiningCore pool , testing it with Litecoin.
Im connected but seeing alot of connection accepted and disconnets. Is that normal?

![2022-04-14_14-25-06](https://user-images.githubusercontent.com/771496/163453892-f133d276-3aec-4a6b-a8a7-9b678fb8d946.jpg)

Also, wondering how long can I expect before seeing my first reward?
Thanks in advance.

**Comment by oliverw** [comment]
Some ASICs appear to be utilizing permanent re-connects to determine pool health status. As to when you can expect a block is something that depends on hashing power and luck and is not really a Miningcore issue.
