### ISSUE TITLE
Two miners with same hash rate but different shares per second

### ISSUE THREAD

**Issue by Fletch153** [oliverw/miningcore#1254]
Forgive me if this isn't a bug, but could anyone confirm if it's normal that two miners with similar hash rates, but a different amount of workers should be getting different quantities of shares per second?

In testing, one miner with a hash rate of 2.5GHs and 30 workers, is getting around 2.5 shares/sec, while the other miner with around 2 GHs and 2 workers is getting a hash rate of around 0.37 shares /sec. Is this expected behavior, and will this affect how each miner is paid using the "PPLNS" configuration?

Any guidance or documentation on this would be much appreciated, thank you!

**Comment by Fletch153** [comment]
Ah, from looking into the code, it looks like each share has a "difficulty" associated with it, so although one of the miners has more shares per second, the difficulty associated with each share is lower, which is taken into account when calculating the share price.  If this is the case then the issue can be closed :-). Thanks.

**Comment by Fletch153** [comment]
Ah, from looking into the code, it looks like each share has a "difficulty" associated with it, so although one of the miners has more shares per second, the difficulty associated with each share is lower, which is taken into account when calculating the share price. If this is the case then the issue can be closed :-). Thanks.

**Comment by oliverw** [comment]
> Ah, from looking into the code, it looks like each share has a "difficulty" associated with it, so although one of the miners has more shares per second, the difficulty associated with each share is lower, which is taken into account when calculating the share price.

Exactly.
