### ISSUE TITLE
ERGO Blocks mined api not updating

### ISSUE THREAD

**Issue by babelfish2001** [oliverw/miningcore#1278]
I have three mined blocks reported on the API. There are three mined blocks showing in my mined to address. The Api for the mined blocks appears to have stopped updating.  Is this a bigger problem that might prevent proper mining?

Also, this is just solo mining for myself. So I wasn't sure what I needed to do for payouts, I just want it to go in to my node address.

Thanks!

ergo.json
{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "ergo_core.log",
        "apiLogFile": "ergo_api.log",
        "logBaseDirectory": "c:/miningcore/build/logs",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "Integrated",
        "banOnJunkReceive": false,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "pool support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": false
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "XXXX",
            "database": "miningcore"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "api": {
        "enabled": true,
        "listenAddress": "127.0.0.1",
        "port": 4000,
        "metricsIpWhitelist": [],
        "rateLimiting": {
            "disabled": false, // disable rate-limiting all-together, be careful
            "rules": [
                {
                    "Endpoint": "*",
                    "Period": "1s",
                    "Limit": 5
                }
            ],
            // List of IP addresses excempt from rate-limiting (default: none)
            "ipWhitelist": []
        }
    },
    "pools": [
        {
            // DON'T change the id after a production pool has begun collecting shares!
            "id": "ergo",
            "enabled": true,
            "coin": "ergo",
            "address": "XXXX", //node wallet
            "rewardRecipients": [
                {
                    //Pool fee wallet
		    "address": "XXXX",
                    "percentage": 100.0
                }
            ],
            "blockRefreshInterval": 200,
            "jobRebroadcastTimeout": 10,
            "clientConnectionTimeout": 600,
            "banning": {
                "enabled": true,
                "time": 600,
                "invalidPercent": 50,
                "checkThreshold": 50
            },
            "ports": {
                // Binding port for your miners to connect to
                "3052": {
                    // Binding address (Default: 127.0.0.1)
                    "listenAddress": "0.0.0.0",
                    "difficulty": 0.9,
                    "tls": false,
                    "tlsPfxFile": "/var/lib/certs/mycert.pfx",
                    "varDiff": {
                        "minDiff": 0.9,
                        "maxDiff": null,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30,
                        "maxDelta": 500
                    }
                },
		"3156": {
                    "name":  "POOL GPU HIGH DIFF",
                    // Binding address (Default: 127.0.0.1)
                    "listenAddress": "0.0.0.0",
                    // Pool difficulty
                    "difficulty": 0.9,
                    // TLS/SSL configuration
                    "tls": false,
                    "tlsPfxFile": "/var/lib/certs/mycert.pfx",
		    "multiplyDifficulty": true,
                    "varDiff": {
                        "minDiff": 1.0,
                        "maxDiff": null,
                        "targetTime": 15,
                        "retargetTime": 30,
                        "variancePercent": 30,
                        "maxDelta": 500
                    }
				}
            },
            "daemons": [
                {
                    "host": "localhost",
                    "port": 9052,
		    "apiKey": "XXXX", //Password. Not Hash Key
                    "zmqBlockNotifySocket": "tcp://127.0.0.1:15101",
                    "portWs": 18545,
                }
            ],
            // Generate payouts for recorded shares
            "paymentProcessing": {
                "enabled": true,
                "minimumPayment": 0.01,
                "payoutScheme": "PPLNS",
                "payoutSchemeConfig": {
                    "factor": 2.0
                }
            }
        }
        // This section ends here. Add `,` after `}` if this is not the last coin section
    ]
}

**Comment by babelfish2001** [comment]
The odd thing is that I haven't hit any block since the API stopped updating.  I removed miningcore and postgre and then reinstalled them. Everything looks like it is mining, but haven't hit a block yet with the new install.  Please help, I just want to make sure that everything is working properly.  

Thanks!

**Comment by oliverw** [comment]
> The odd thing is that I haven't hit any block since the API stopped updating. I removed miningcore and postgre and then reinstalled them. Everything looks like it is mining, but haven't hit a block yet with the new install. Please help, I just want to make sure that everything is working properly.
> 
> How does miningcore know when to submit the solution to the network? And is there a way to ensure that that part of the program is running properly?

https://github.com/oliverw/miningcore/blob/f519f719a990d3e36a20355ea38f96460fb1c95e/src/Miningcore/Blockchain/Ergo/ErgoJob.cs#L148

**Comment by oliverw** [comment]
Closing until there is more information added.
