### ISSUE TITLE
Monero Daemon and RPC Wallet

### ISSUE THREAD

**Issue by minershaven** [oliverw/miningcore#1284]
i have miningcore and monero running on 2 different servers.  right now when i start up my wallet rpc im using 

monero-wallet-rpc --daemon-address 127.0.0.1:18081 --wallet-file=/my path to wallet --rpc-bind-ip 127.0.0.1 --rpc-bind-port 18083 --log-level 1 --disable-rpc-login --prompt-for-password

do i need to change the rpc bind ip to the server ip miningcore is on ?   I cant seem to get the 2 to talk to each other all i get is 

[I] [vertcoin] Stratum ports 0.0.0.0:3060 online
[2022-06-29 15:55:34.9399] [I] [vertcoin] Detected new block 1796452 [POLL]
[2022-06-29 15:55:34.9399] [I] [vertcoin] Broadcasting job 00000002
[2022-06-29 15:55:38.2976] [I] [xmr1] Waiting for daemons to come online ...
[2022-06-29 15:55:43.1944] [I] [StatsRecorder] [vertcoin] Updating Statistics for pool
[2022-06-29 15:55:43.2215] [I] [StatsRecorder] Performing Stats GC
[2022-06-29 15:55:43.2215] [I] [StatsRecorder] [vertcoin] Reset performance stats for pool
[2022-06-29 15:55:43.2345] [I] [StatsRecorder] Stats GC complete
[2022-06-29 15:55:48.2996] [I] [xmr1] Waiting for daemons to come online ...
[2022-06-29 15:55:58.2952] [I] [xmr1] Waiting for daemons to come online ...
[2022-06-29 15:56:08.2949] [I] [xmr1] Waiting for daemons to come online ...
[2022-06-29 15:56:18.2944] [I] [xmr1] Waiting for daemons to come online ...
[2022-06-29 15:56:23.9057] [I] [vertcoin] Broadcasting job 00000003

**Comment by machinasapiens** [comment]
Does Monero still works with Miningcore? 

I have my Monero fully synced and all I see on Miningcore is "[xmr1] Waiting for daemons to come online ..." .
 
Appreciate any help. Thanks.

**Comment by oliverw** [comment]
> Does Monero still works with Miningcore?
> 
> I have my Monero fully synced and all I see on Miningcore is "[xmr1] Waiting for daemons to come online ..." .
> 
> Appreciate any help. Thanks.

It is supposed to. You probably forgot to configure the wallet daemon.

**Comment by machinasapiens** [comment]
@oliverw That was a quick answer :)

This is how I am running it. I tried so many different combinations in the last days... going crazy here. 

My Monero node is running on a machine at 192.168.3.203:

`DNS_PUBLIC="tcp://8.8.8.8" monerod --log-file /dev/null --non-interactive --rpc-bind-ip 192.168.3.203 --rpc-bind-port 18081 --rpc-login miningcore:(mypassword)--out-peers 32 --p2p-bind-ip 0.0.0.0 --p2p-bind-port 18080 --confirm-external-bind`

`DNS_PUBLIC="tcp://8.8.8.8"` monero-wallet-rpc --daemon-address 192.168.3.203:18081 --daemon-login miningcore:(mypassword)--wallet-file=/root/wallets/pool-wallet.dat --password "(walletpassword)" --rpc-bind-port 18082 --rpc-bind-ip 192.168.3.203 --log-level 1 --confirm-external-bind --trusted-daemon --disable-rpc-login
`

My Miningcore is running on a different machine at 192.168.3.100.  Please notice that I have several other coins working perfectly fine on Miningcore (Bitcoin family and Ethereum) and I am only strugling with Monero.

My Miningcore settings for Monero:

`
    // monero ------ begin

    {
      "id": "xmr1",
      "enabled": false,
      "coin": "monero",
      "randomXRealm": "xmr1",
      "address": "(redacted)", // this is the address of the wallet I am opening with monero-wallet-rpc
      "rewardRecipients": [
        {
          "address": "(walletaddress)", // another monero wallet
          "percentage": 1
        }
      ],
      "blockRefreshInterval": 500,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "5555": {
          "listenAddress": "0.0.0.0",
          "difficulty": 7500,
          "name": "CPU Mining",
          "varDiff": {
            "minDiff": 1000,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        },
        "5556": {
          "listenAddress": "0.0.0.0",
          "difficulty": 25000,
          "name": "GPU Mining",
          "varDiff": {
            "minDiff": 10000,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        },
        "5557": {
          "listenAddress": "0.0.0.0",
          "difficulty": 200000,
          "name": "High-End Multi GPU Mining",
          "varDiff": {
            "minDiff": 200000,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 120,
            "variancePercent": 30
          }
        }
      },
      "daemons": [
        {
          "host": "192.168.3.203",
          "port": 18081,
          "user": "miningcore",
          "password": "(mypassword)"
       },
        {
          "host": "192.168.3.203",
          "port": 18082,
          "user": "miningcore",
          "password": "(mypassword)",
          "category": "wallet"
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.25,
        "minimumPaymentToPaymentId": 1.0,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }

    // monero ------- end`

Appreciate your work and willing to collaborate with you. Thanks.
