### ISSUE TITLE
ERGO payout error

### ISSUE THREAD

**Issue by goodthebest** [oliverw/miningcore#1287]
ERGO payout were going smoothly but suddenly payouts not working and I got this error. Any thoughts?

![image](https://user-images.githubusercontent.com/1715740/177013847-b34427e1-2423-45a7-9a6f-a7d655cb15bc.png)

**Comment by oliverw** [comment]
Should work on dev branch.

**Comment by goodthebest** [comment]
Currently I'm using V69, instead I should run Dev branch, please advise?

**Comment by oliverw** [comment]
Or wait for v70 on monday

Oliver Weichhold
________________________________
Von: Linux server management, OS softwares and applications, blockchain Mining Pools, Daemons ***@***.***>
Gesendet: Saturday, July 2, 2022 9:30:44 PM
An: oliverw/miningcore ***@***.***>
Cc: Oliver Weichhold ***@***.***>; Comment ***@***.***>
Betreff: Re: [oliverw/miningcore] ERGO payout error (Issue #1287)


Currently I'm using V69, instead I should run Dev branch, please advise?

**Comment by goodthebest** [comment]
with Dev branch I'm having the same payout issue?

**Comment by goodthebest** [comment]
cool, lookin forward to v70.
