### ISSUE TITLE
v70, batch build script is broken

### ISSUE THREAD

**Issue by goodthebest** [oliverw/miningcore#1305]
**Describe the bug**
build script is broken

**To Reproduce**
run
**./build-ubuntu-20.04.sh**

**Screenshots**
![image](https://user-images.githubusercontent.com/1715740/178055525-eac203f9-81d5-4140-9f18-8d832c3c5758.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04

**Comment by oliverw** [comment]
How did you get the source code?

**Comment by goodthebest** [comment]
https://github.com/oliverw/miningcore/releases/tag/v70

downloaded tarball

**Comment by oliverw** [comment]
> https://github.com/oliverw/miningcore/releases/tag/v70
> 
> downloaded tarball

That's the problem. Clone the repo please. 

I know it should be documented but I'm waiting for package GitVersion.MsBuild to fix that.
