### ISSUE TITLE
ERGO: TRM doesn't work

### ISSUE THREAD

**Issue by Censseo** [oliverw/miningcore#1306]
With  TRM v 0.10.2, on MC v70, no SSL, get this error:
![image](https://user-images.githubusercontent.com/3895982/178107021-9465b284-fc21-4000-a109-a28b05b14058.png)
Tried to bypass with --pool_broken_rpc but no effect.

**Comment by oliverw** [comment]
Duplicate of #1217

**Comment by Censseo** [comment]
So no solution?
