### ISSUE TITLE
Network Hashrate on Build 70

### ISSUE THREAD

**Issue by MiningCryptoLive** [oliverw/miningcore#1312]
after building the latest release the network hashrate show in KH/s instead of TH/s. How do I fix this?

**Comment by SsNiPeR1** [comment]
you can still build older version if you don't like the newer

**Comment by ei8ht187** [comment]
no you can't. Older versions don't support EIP27 on ERGO...

**Comment by oliverw** [comment]
> after building the latest release the network hashrate show in KH/s instead of TH/s. How do I fix this?

I'll look into it.
