### ISSUE TITLE
ETH payout: invalid sender

### ISSUE THREAD

**Issue by SsNiPeR1** [oliverw/miningcore#1313]
[eth1] System.Exception: eth_sendTransaction returned error: invalid sender code -32000

**Comment by SsNiPeR1** [comment]
the similar thing is happening with etherumjs-tx, but ethereumjs-common fixes this.

**Comment by SsNiPeR1** [comment]
@oliverw please help I need to set up pool on this week

**Comment by SsNiPeR1** [comment]
still no help 😢

**Comment by Konstantin35** [comment]
What network are you using for testing

**Comment by SsNiPeR1** [comment]
> What network are you using for testing

It is my private chain, you won't find it

**Comment by SsNiPeR1** [comment]
ah yes, payout does not work but that's not the issue, we won't fix this!

**Comment by ghost** [comment]
Did you find any fix 
i am having same problem
