### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by feculay** [oliverw/miningcore#1338]
**Describe the bug**
in windows:
[2022-08-01 07:09:59.9099] [I] [feculaypool] New work at height 15648229 and header 0x34176333e7c4ce9972d19a6fdbc994812d9b2644d952a9305062aabc3562ead3 via [POLL]
[2022-08-01 07:09:59.9099] [I] [feculaypool] Broadcasting job 00000006
[2022-08-01 07:10:06.6946] [I] [feculaypool] New work at height 15648229 and header 0x833153af4829996758f95f791d1286f45f29f34b2b0a37c692530454ed426776 via [POLL]
[2022-08-01 07:10:06.7008] [I] [feculaypool] Broadcasting job 00000007
[2022-08-01 07:10:07.2285] [I] [feculaypool] Pre-generating DAG for epoch 522
[2022-08-01 07:10:07.2285] [I] [feculaypool] Generating DAG for epoch 522
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by oliverw** [comment]
Most likely a problem with available RAM or disk space.

**Comment by feculay** [comment]
> Most likely a problem with available RAM or disk space.

good morning, thank you very much for your answer, query: how do I configure for ethereum classic?

**Comment by oliverw** [comment]
ETC is currently not supported buts it's on my list.

**Comment by feculay** [comment]
> ETC is currently not supported buts it's on my list.

thank you

**Comment by feculay** [comment]
Mining ore not support etc?

**Comment by seperatis** [comment]
@feculay, as OliverW has already explained, Ethereum Classic is not supported on Miningcore (yet), but might be in the future.
Please see this list for supported coins: https://github.com/oliverw/miningcore/blob/master/src/Miningcore/coins.json

**Comment by Decidueye10** [comment]
Got this exact same error, but I have 20gb free RAM and 100gb free disk space. 
I tried restarting everything, but the same error appears. This happens exactly when miningcore pre-generates the next dag.

**Comment by oliverw** [comment]
> Got this exact same error, but I have 20gb free RAM and 100gb free disk space. I tried restarting everything, but the same error appears. This happens exactly when miningcore pre-generates the next dag. Perhaps there's some error somewhere and not the availability of RAM and disk space? I tried setting the same miningcore build with my ERGO node and it works just fine.

Is this on Windows?

**Comment by Decidueye10** [comment]
Yes on Windows, same as above

**Comment by oliverw** [comment]
> **Describe the bug** in windows: 

Just noticed this. DAG generation on Windows is notoriously unreliable and that's one of the reasons why running MC on Windows in **production** is not supported. I realize and apologize that this has not been explicitly stated in the README in the past, but that's been corrected now.
