### ISSUE TITLE
Error during Ubuntu 20.04 build

### ISSUE THREAD

**Issue by TimyIsCool** [oliverw/miningcore#1339]
![image](https://user-images.githubusercontent.com/74112751/182833782-174e77dd-1632-41af-957f-5e24d4434dd1.png)
I am getting that error when I run Ubuntu-build-20.04.sh

**Comment by TimyIsCool** [comment]
Found the issue

**Comment by t-ibrahim-t** [comment]
can you tell me how to fix this
