### ISSUE TITLE
Lack of updated documentation for Monero

### ISSUE THREAD

**Issue by machinasapiens** [oliverw/miningcore#1347]
It seems to be impossible to make Monero work on Miningcore with the current info available here.

I found a contradition in the available documentation.

At https://github.com/oliverw/miningcore/wiki/Coin-Daemon-&-Wallet-RPC you recommend starting the monero-wallet-rpc with:

$ monero-wallet-rpc --daemon-address 127.0.0.1:18081 --wallet-file=<wallet-file-path> --rpc-bind-port 18082 --rpc-bind-ip 127.0.0.1 ```--rpc-login <username>:<password>``` --log-level 1

But at the same time, at https://github.com/oliverw/miningcore/blob/master/README.md#caveats you recomnend to run it with ```--disable-rpc-login``` otherwise Monero will not work.

I can't just add ```--disable-rpc-login``` to the command line because the monero-rpc-wallet would say ```Cannot specify --disable-rpc-login and --rpc-login``` .

I tried everything. Nothing works. I can not simply guess what to do.

Miningcore keeps showing this:
[2022-08-13 17:05:57.8330] [I] [xmr1] Waiting for daemons to come online ...

Apprecciate any kind soul could help me. I would like to have the correct command lines to run monerod and monero-wallet-rpc and also need the pool settings for monero. None of the examples available here are working for me.

Running Ubuntu 20.04.4 LTS

Thank you.

**Comment by xmrstickers** [comment]
You should disable RPC login -- miningcore is very transparent with the fact that it cannot handle HTTP digest auth 

what happens when you simply try to run it with --disable-rpc-login alone? do not use --rpc-login

**Comment by machinasapiens** [comment]
Hello @xmrstickers! Thanks for the help! :)

I already tried. Nothing changed:

[2022-08-13 17:51:55.1509] [I] [xmr1] Waiting for daemons to come online ...
[2022-08-13 17:51:55.7495] [I] [xmr1] Waiting for daemons to come online ...

My monerod:

DNS_PUBLIC="tcp://8.8.8.8"  /root/monero/monerod --non-interactive --rpc-bind-ip 192.168.3.203 --out-peers 32 --p2p-bind-ip 192.168.3.203 --p2p-bind-port 18080 --confirm-external-bind

My monero-wallet-rpc:

DNS_PUBLIC="tcp://8.8.8.8" /root/monero/monero-wallet-rpc --daemon-address 192.168.3.203:18081 --wallet-file=/root/wallets/pool-wallet.dat --password "123456" --rpc-bind-port 18082 --rpc-bind-ip 192.168.3.203 --rpc-login miningcore:123456 --log-level 1 --confirm-external-bind

My daemons on config.json:

        {
          "host": "192.168.3.203",
          "port": 18081,
          "user": "miningcore",
          "password": "123456"
       },
        {
          "host": "192.168.3.203",
          "port": 18082,
          "user": "miningcore",
          "password": "123456",
          "category": "wallet"
        }

My software:

Ubuntu 20.04.4 LTS
Monero 'Fluorine Fermi' (v0.18.1.0-release)
Miningcore 69.0.1.0-master [3e313fda148e00d2aa17d047126df358813da66d]

![image](https://user-images.githubusercontent.com/111072336/184505674-4830bb9d-61ad-49b9-b5d4-46899f8949cd.png)

**Comment by xmrstickers** [comment]
are you sure? `_--rpc-login miningcore:123456_` still present under "My monero-wallet-rpc:"

**Comment by machinasapiens** [comment]
@xmrstickers 

> are you sure? `_--rpc-login miningcore:123456_` still present under "My monero-wallet-rpc:"

OMG. I did it and undid soo many times that I am confused now. Sorry. Now I have it right:

DNS_PUBLIC="tcp://8.8.8.8" /root/monero/monero-wallet-rpc --daemon-address 192.168.3.203:18081 --wallet-file=/root/wallets/pool-wallet.dat --password "123456" --rpc-bind-port 18082 --rpc-bind-ip 192.168.3.203 --log-level 1 --confirm-external-bind --disable-rpc-login

Miningcore now can see the monero daemons, but can not connect. I see this error in the log:

[2022-08-13 18:24:03.1506] [I] [xmr1] All daemons synched with blockchain                                                                                   [2022-08-13 18:24:03.1833] [E] [xmr1] System.DllNotFoundException: Unable to load shared library 'libcryptonote' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibcryptonote: cannot open shared object file: No such file or directory   at Miningcore.Native.CryptonoteBindings.decode_address(Byte* input, Int32 inputSize)                                                                        (cut)                                                          

![image](https://user-images.githubusercontent.com/111072336/184506502-4c4abaa1-d725-43bf-93ca-cd4472101174.png)

Do you know what is causing this?

Thank you.

**Comment by xmrstickers** [comment]
No problem, sometimes you just need another pair of eyes. 

Keep in mind, monero JUST hard-forked not even 5 minutes ago -- if you are not on version v0.18.1.0 then you will be unable to transact with the monero network later today. There could  be issues with the release relative to miningcore; I just don't know.

**Comment by machinasapiens** [comment]
> No problem, sometimes you just need another pair of eyes.
> 
> Keep in mind, monero JUST hard-forked not even 5 minutes ago -- if you are not on version v0.18.1.0 then you will be unable to transact with the monero network later today. There could be issues with the release relative to miningcore; I just don't know.

I say it on my log before. I was already running the new Monero.

2022-08-13 17:20:55.092 [P2P2]  INFO    global  src/cryptonote_core/cryptonote_core.cpp:1835    Version 0.18.1.0 of monero for linux-x64 is available: https://downloads.getmonero.org/cli/monero-linux-x64-v0.18.1.0.tar.bz2, SHA256 hash 9318e522a5cf95bc856772f15d7507fdef2c028e01f70d020078ad5e208f1304


Thank you.

**Comment by machinasapiens** [comment]
[SOLVED]
