### ISSUE TITLE
Fix request for "Coin-Daemon-&-Wallet-RPC" Wiki page (Monero section)

### ISSUE THREAD

**Issue by machinasapiens** [oliverw/miningcore#1348]
On https://github.com/oliverw/miningcore/wiki/Coin-Daemon-&-Wallet-RPC#monero the following line needs to be changed...

From this: 
`$ monero-wallet-rpc --daemon-address 127.0.0.1:18081 --wallet-file=<wallet-file-path> --rpc-bind-port 18082 --rpc-bind-ip 127.0.0.1 --rpc-login <username>:<password> --log-level 1`

To this:
`$ monero-wallet-rpc --daemon-address 127.0.0.1:18081 --wallet-file=<wallet-file-path> --rpc-bind-port 18082 --rpc-bind-ip 127.0.0.1 --disable-rpc-login --log-level 1`

I do not have permission to fix it, otherwise I would.

Thanks.

**Comment by seperatis** [comment]
This is not a bug. Please do not open New issues unless they are **directly related** to MC software itself; the code base. 

For everything else, we have: https://github.com/oliverw/miningcore/discussions

**Comment by seperatis** [comment]
@machinasapiens 

I have updated the WIKI page. 
In the future please use Discussions for anything that is not directly code-base related.
Thanks.
