### ISSUE TITLE
Waiting for daemons to come online ...

### ISSUE THREAD

**Issue by 1n4ho05** [oliverw/miningcore#1360]
Hello,

I just installed miningcore and downloaded the blockchain. But when I run miningcore I receive the message: Waiting for daemons to come online ...

This is how I launched the litecoin daemon: litecoind -server -datadir= -rpcuser= -rpcpassword= -port=9333 -rpcport=9332 -rpcbind=0.0.0.0

What wrong with that? How many litecoin daemons should I run, and how?

Thank you.

**Comment by seperatis** [comment]
@1n4ho05 

Stop opening up new issues for this. This is **the second time in 24 hours** for the same Question.
I converted the issue into a Discussion here: https://github.com/oliverw/miningcore/discussions/1361, so please follow it for an answer to your Question.

Everyone, please _only_ open a **new issue** for problems that are directly **code related**

If you do not know how to configure Miningcore, the coin daemons, or don't understand basic Linux & server configurations, **that is not a bug** and it belongs in a Discussion. Don't open an Issue for this.

PS - You can also find a _wealth of information_ by searching **Closed Issues** ;-)

**Comment by idanzam** [comment]
https://github.com/oliverw/miningcore/discussions/1361 - no page!
