### ISSUE TITLE
block stays on pending forever instead of being orphaned

### ISSUE THREAD

**Issue by Censseo** [oliverw/miningcore#1362]
Hello,

Since we start our ergo pool, we got some orphan blocks. But for the most of them, miningcore never reports them as orphan, just staying pending with 0% at confirmation, and with sometime 0 as reward also.
For exemple, two blocks mined, one ok, and one orphan but stays pending:

```
{
    "poolId": "ergo1",
    "blockHeight": 818254,
    "networkDifficulty": 349593.68107177434,
    "status": "confirmed",
    "confirmationProgress": 1,
    "effort": 0.0010872191350888827,
    "transactionConfirmationData": "807f69dcc39b80bc",
    "reward": 48.002000000000,
    "infoLink": "https://explorer.ergoplatform.com/en/blocks/44c6f9065cab9a7c4c4b699928bb732ef4ee70b2045c00f7ba72fd7a08dceabf",
    "hash": "44c6f9065cab9a7c4c4b699928bb732ef4ee70b2045c00f7ba72fd7a08dceabf",
    "miner": "9fRFe7nEjDu464eZggQ4yY4ugRsp7ZiS6rNNAYWdwhT6nhUHqgh",
    "created": "2022-08-17T20:15:48.990627Z"
  },
  {
    "poolId": "ergo1",
    "blockHeight": 818177,
    "networkDifficulty": 349593.68107177434,
    "status": "pending",
    "confirmationProgress": 0,
    "effort": 0.006110666537590124,
    "transactionConfirmationData": "86ba0011f9dd5650",
    "reward": 48.007534000000,
    "infoLink": "https://explorer.ergoplatform.com/en/blocks/0b67e7dbe4188059c8d528045343df62f163ebc17d4b3aafe23574dbb0683d8c",
    "hash": "0b67e7dbe4188059c8d528045343df62f163ebc17d4b3aafe23574dbb0683d8c",
    "miner": "9iCHMGWegsnQ8AURdVwABrefXta6B5mX3DMyHbS23kC3A6V11qv",
    "created": "2022-08-17T17:56:16.364445Z"
  },
```

Also, I have the feeling that one block at least got never confirmed bu miningcore, but we still got it anyway, so it never get paid (I can see my balance corresponding at fees+one block)

**Comment by ei8ht187** [comment]
Do you use separate nodes for mining an payout? If so, did you set the mining pub key, the one starting with 88, in your mining nodes config?

**Comment by Censseo** [comment]
> Do you use separate nodes for mining an payout? If so, did you set the mining pub key, the one starting with 88, in your mining nodes config?

No

**Comment by fer000n** [comment]
same problem in 3 blocks

Found Time	Finder	Height	Net Diff	Luck	Status	Reward	Confirmation
Sun Oct 23 2022 07:34:57 GMT+0330 (Iran Standard Time)	9hs6FVJc … 5sVPYZpK	[858605](https://explorer.ergoplatform.com/en/blocks/f18be39a58720969251f9e4b5568bafb139723f0dd7efb11144ff7fc67af0f7e)	1.41909 MH/s	0%	Pending	45.1321	
0% Completed
Tue Oct 18 2022 03:21:41 GMT+0330 (Iran Standard Time)	9hxKTqta … HjNaMeVD	[854929](https://explorer.ergoplatform.com/en/blocks/f03d977f558d5957e654ae5a307ea1593bc60d6a6c2337caa00627217d7cfbe6)	1.45565 MH/s	0%	Pending	45.0501	
0% Completed
Wed Oct 12 2022 01:02:42 GMT+0330 (Iran Standard Time)	9gSjzEpB … 5EtHijA1	[850607](https://explorer.ergoplatform.com/en/blocks/83631d62ee33305c63d7acd107a9d5d16a80a46167eb0d18b9828db25471d8a9)	1.85712 MH/s	0%	Confirmed	45.022	
100% Completed
Sat Oct 01 2022 02:33:18 GMT+0330 (Iran Standard Time)	9i76iG1y … rYmEWdzU	[844415](https://explorer.ergoplatform.com/en/blocks/82bb4650059dae5ae3ef0a3b97fc0a49c6d412b5cae3e315a378f96b5291b7b4)	3.8674 MH/s	0%	Confirmed	48.0375	
100% Completed
Tue Sep 27 2022 10:57:01 GMT+0330 (Iran Standard Time)	9hs6FVJc … 5sVPYZpK	[843975](https://explorer.ergoplatform.com/en/blocks/0e01bb85dfffb430212905129316665c548334dfe04fd0892bdae2b67fd5831f)	3.8674 MH/s	0%	Pending	48.06146	
0% Completed

**Comment by fer000n** [comment]
I spoke with one of ergo developers and he said the cause of this is delay between my node and other nodes so we must use a highspeed VPS for hosting node but in MC after restarting node shows Orphan.

**Comment by idanzam** [comment]
Use LEGACY address only on config.json at pool area

coind  getnewaddress "legacy"
