### ISSUE TITLE
Support Etc 

### ISSUE THREAD

**Issue by feculay** [oliverw/miningcore#1369]
Please support etc

**Comment by seperatis** [comment]
@feculay 

Please, let's only open _new issues_ for bugs/problems related directly to Miningcore's code. 
For feature requests, coin addition requests, etc, the Discussions page is a better place.

_If_ you would have searched the Discussions section, you would have seen that ETC is on OliverW's map already.
https://github.com/oliverw/miningcore/discussions/850

Please everyone, always search old issues, and Discussions before creating new ones, as you can often find your answer there.

Regards
