### ISSUE TITLE
MIKE Algo Support?

### ISSUE THREAD

**Issue by Chadwicksracing** [oliverw/miningcore#1373]
https://github.com/Qkax/cpuminer-mike/tree/master/algo/mike

for vKAX coin

**Comment by totom9000** [comment]
Offered this to oliverw  yesterday as mining4people.com  my pool has this algo and only MC pool with this he dont want it.

**Comment by oliverw** [comment]
> Offered this to oliverw yesterday as mining4people.com my pool has this algo and only MC pool with this he dont want it.

Stop pretending that you guys offered it out of kindness, you wanted something worth hundreds of dollars in exchange for it.
