### ISSUE TITLE
Ergo worker names are not displayed correctly in miningcore 

### ISSUE THREAD

**Issue by xmrstickers** [oliverw/miningcore#1378]
I've noticed strange behavior in Miningcore with workers: depending on your mining client, they will not show on miningcore CLI/Logs, however, I can confirm T-REX on windows (with the -w flag) does show up - but only on the logs. 

when looking at the API under _/api/pools/POOL_NAME/miners/ERGO_WALLET_ADDRESS_ no worker names are displayed. 

I have tested Lolminer 1.52+ on Linux and T-rex 0.26.14 on windows.

**Comment by Kali123411** [comment]
I'm having this exact issue, all my workers are using T-rex and only the two T-rex workers on HiveOS are reporting worker name on my webpage UI

**Comment by jvxis** [comment]
I need to use on HIVEOS the template %WAL%.%WORKER_NAME%. Doing this, the worker name is appearing.

**Comment by oliverw** [comment]
> I've noticed strange behavior in Miningcore with workers: depending on your mining client, they will not show on miningcore CLI/Logs, however, I can confirm T-REX on windows (with the -w flag) does show up - but only on the logs.
> 
> when looking at the API under _/api/pools/POOL_NAME/miners/ERGO_WALLET_ADDRESS_ no worker names are displayed.
> 
> I have tested Lolminer 1.52+ on Linux and T-rex 0.26.14 on windows.

That is the intended behavior. Worker names are only available for the `{poolId}/miners/{address}/performance` endpoint.

**Comment by xmrstickers** [comment]
@oliverw - this behavior still happens on that end-point. No worker names are listed. 
![image](https://user-images.githubusercontent.com/89484281/187276741-3f51f237-06c5-42ef-b276-d52ebd1e4b7f.png)
