### ISSUE TITLE
Ergo worker names are not displayed correctly in miningcore 

### ISSUE THREAD

**Issue by xmrstickers** [oliverw/miningcore#1379]
I've noticed strange behavior in Miningcore with workers: depending on your mining client, they will not show on miningcore CLI/Logs, however, I can confirm T-REX on windows (with the -w flag) does show up - but only on the logs.

when looking at the API under _/api/pools/POOL_NAME/miners/ERGO_WALLET_ADDRESS/performance_ no worker names are displayed.

I have tested Lolminer 1.52+ on Linux and T-rex 0.26.14 on windows.

![image](https://user-images.githubusercontent.com/89484281/187276741-3f51f237-06c5-42ef-b276-d52ebd1e4b7f.png)

(sorry I did not include "performance" in original issue. I believe I have described it properly now, and you can see no workers are shown in the above screenshot) 

_Originally posted by @xmrstickers in https://github.com/oliverw/miningcore/issues/1378#issuecomment-1230724446_

**Comment by MiningCryptoLive** [comment]
You must have something wrong in either your config or miningcore build. I just checked my pool and it works fine. 

![Screenshot_20220829-153454.png](https://user-images.githubusercontent.com/1049926/187283750-7e530e8a-5ec5-4abf-a8a1-9d588f5ca5e6.png)

**Comment by xmrstickers** [comment]
May I ask what mining software and version you are using to get the workers to show? @MiningCryptoLive

**Comment by MiningCryptoLive** [comment]
> May I ask what mining software and version you are using to get the workers to show? @MiningCryptoLive 
> 
> I can't imagine what config setting would be the issue here but I will look again. 

I am using the latest version of miningcore. I really think it's probably a mining software setting that could be incorrect

**Comment by xmrstickers** [comment]
I think so too, that is why I am asking what software is working on your end for mining. 

T-Rex passes the -w flag for worker, for example, and I can see in miningcore logs that indeed, the worker name is present. So that is the reason I thought it was miningcore's fault.

**Comment by xmrstickers** [comment]
Solution: Not miningcore's fault. Do not pass worker name by built-in flag with T-rex or Lolminer -- instead, use: 
<address>.<worker_name> 

Closing issue. Thanks for your help either way @MiningCryptoLive !

**Comment by MiningCryptoLive** [comment]
> Solution: Not miningcore's fault. Do not pass worker name by built-in flag with T-rex or Lolminer -- instead, use: 
> `<address>.<worker_name>` 
> 
> Closing issue. Thanks for your help either way @MiningCryptoLive ! 

Glad you figured it out.
