### ISSUE TITLE
Tcp connection closing after banning disabled

### ISSUE THREAD

**Issue by Kali123411** [oliverw/miningcore#1382]
![image](https://user-images.githubusercontent.com/64617127/187824983-e979fdc7-c38c-4e28-a1a8-829b934b93f9.png)
**Describe the bug**
Today my ergo pool was disconnecting all workers for two hours, until I noticed that stats were not updating on the webpage. From what I can tell my ergo node never went out of sync, so unsure what is causing miningcore to close all the tcp connection repeatedly.

**Comment by jvxis** [comment]
@Kali123411 Did you find a solution?

**Comment by Kali123411** [comment]
> @Kali123411 Did you find a solution?

No the problem hasn't happened again, did it happen to you?

**Comment by jvxis** [comment]
> > @Kali123411 Did you find a solution?
> 
> No the problem hasn't happened again, did it happen to you?

your banning parameter still disabled?

**Comment by oliverw** [comment]
Those disconnects are most likely caused by non-mining clients connecting to the pool - aka script kiddies.
