### ISSUE TITLE
MC is closing worker connections

### ISSUE THREAD

**Issue by jvxis** [oliverw/miningcore#1392]
**Describe the bug**
My workers are getting disconnected from time to time and 2 a 3 minutes later they connected again. My node is synced and running. I tried with banning enabled and also disabled, same behaviour. I changed ports, same behaviour. I changed diff, again same behaviour.

**To Reproduce**
Just run and connect a worker. It seems that with more workers connected the problem happens sooner.

**Expected behavior**
Not get disconnected

**Screenshots**
MC Debug screenshot when the two workers had the connection closed
![image](https://user-images.githubusercontent.com/108929149/188121709-820fcc6c-b7cb-46cf-b78e-bd569f958786.png)

**Desktop (please complete the following information):**
Ubuntu 20.04 VPS 16vcpus / 32gb ram / SSD

My config file.
{
    "logging": {
        "level": "debug",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        // Log file name (full log) - can be null in which case log events are written to console (stdout)
        "logFile": "core.log",
        // Log file name for API-requests - can be null in which case log events are written to either main logFile or console (stdout)
        "apiLogFile": "api.log",
        // Folder to store log file(s)
        "logBaseDirectory": "/friendspool/miningcore/logs", // or c:\path\to\logs on Windows
        // If enabled, separate log file will be stored for each pool as <pool id>.log
        // in the above specific folder.
        "perPoolLogFile": false
    },
    "banning": {
        // "integrated" or "iptables" (linux only - not yet implemented)
        "manager": "Integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "pool support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": false
        }
    },
    // Where to persist shares and blocks to
    "persistence": {
        // Persist to postgresql database
        "postgres": {
            "host": "127.0.0.1",
            "port": 5432,
            "user": "miningcore",
            "password": "pass",
            "database": "miningcore"
        }
    },
    // Generate payouts for recorded shares and blocks
    "paymentProcessing": {
        "enabled": true,
        // How often to process payouts, in milliseconds
        "interval": 600,
        // Path to a file used to backup shares under emergency conditions, such as
        // database outage
        "shareRecoveryFile": "recovered-shares.txt"
    },
    // API Settings
    "api": {
        "enabled": true,
        // Binding address (Default: 127.0.0.1)
        "listenAddress": "0.0.0.0",
        // Binding port (Default: 4000)
        "port": 4000,
        // IP address whitelist for requests to Prometheus Metrics (default 127.0.0.1)
        "metricsIpWhitelist": [],
        // Limit rate of requests to API on a per-IP basis
        "rateLimiting": {
            "disabled": false, // disable rate-limiting all-together, be careful
            // override default rate-limit rules, refer to https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/IpRateLimitMiddleware#defining-rate-limit-rules
            "rules": [
                {
                    "Endpoint": ".+",
                    "Period": "1s",
                    "Limit": 10
                }
            ],
            // List of IP addresses excempt from rate-limiting (default: none)
            "ipWhitelist": []
        }
    },
    "pools": [
        // Repeat the following section for multiple coins
        {
            // DON'T change the id after a production pool has begun collecting shares!
            "id": "ergo1",
            "enabled": true,
            "coin": "ergo",
            // Address to where block rewards are given (pool wallet)
            "address": "wallet",
            "maxActiveJobs": 300,
            // Block rewards go to the configured pool wallet address to later be paid out
            // to miners, except for a percentage that can go to, for examples,
            // pool operator(s) as pool fees or or to donations address. Addresses or hashed
            // public keys can be used. Here is an example of rewards going to the main pool
            // "op"
            "rewardRecipients": [
                {
                    // Pool wallet
                    "address": "wallet",
                    "percentage": 0.5
                }
            ],
            // How often to poll RPC daemons for new blocks, in milliseconds
            "blockRefreshInterval": 300,
            // Some miner apps will consider the pool dead/offline if it doesn't receive
            // anything new jobs for around a minute, so every time we broadcast jobs,
            // set a timeout to rebroadcast in this many seconds unless we find a new job.
            // Set to zero to disable. (Default: 0)
            "jobRebroadcastTimeout": 40,
            // Remove workers that haven't been in contact for this many seconds.
            // Some attackers will create thousands of workers that use up all available
            // socket connections, usually the workers are zombies and don't submit shares
            // after connecting. This features detects those and disconnects them.
            "clientConnectionTimeout": 320,
            // If a worker is submitting a high threshold of invalid shares, we can
            // temporarily ban their IP to reduce system/network load.
            "banning": {
                "enabled": true,
                // How many seconds to ban worker for
                "time": 600,
                // What percent of invalid shares triggers ban
                "invalidPercent": 90,
                // Check invalid percent when this many shares have been submitted
                "checkThreshold": 150
            },
            // Each pool can have as many ports for your miners to connect to as you wish.
            // Each port can be configured to use its own pool difficulty and variable
            // difficulty settings. 'varDiff' is optional and will only be used for the ports
            // you configure it for.
            "ports": {

                "41423": {
                    "name": "Low Fixed Diff",
                    // Binding address (Default: 127.0.0.1)
                    "listenAddress": "0.0.0.0",
                    // Pool difficulty
                    "difficulty": 0.931315,
                    // TLS/SSL configuration
                    "tls": false,
                    "tlsPfxFile": "/var/lib/certs/mycert.pfx",
                    //"multiplyDifficulty": true,
                    // Variable difficulty is a feature that will automatically adjust difficulty
                    // for individual miners based on their hash rate in order to lower
                    // networking overhead
                    "varDiff": {
                        // Minimum difficulty
                        "minDiff": 0.931315,
                        // Maximum difficulty. Network difficulty will be used if it is lower than
                        // this. Set to null to disable.
                        "maxDiff": 0.931315,
                        // Try to get 1 share per this many seconds
                        "targetTime": 15,
                        // Check to see if we should retarget every this many seconds
                        "retargetTime": 90,
                        // Allow time to very this % from target without retargeting
                        "variancePercent": 30,
                        // Do not alter difficulty by more than this during a single retarget in
                        // either direction
                        "maxDelta": 500
                    }
                },

                // Binding port for your miners to connect to Jaime:Fixed Difficulty
                "41424": {
                    "name": "High fixed Diff",
                    // Binding address (Default: 127.0.0.1)
                    "listenAddress": "0.0.0.0",
                    // Pool difficulty
                    "difficulty": 0.931315,
                    // TLS/SSL configuration
                    "tls": false,
                    "tlsPfxFile": "/var/lib/certs/mycert.pfx",
                    "multiplyDifficulty": true,
                    // Variable difficulty is a feature that will automatically adjust difficulty
                    // for individual miners based on their hash rate in order to lower
                    // networking overhead
                    "varDiff": {
                        // Minimum difficulty
                        "minDiff": 5,
                        // Maximum difficulty. Network difficulty will be used if it is lower than
                        // this. Set to null to disable.
                        "maxDiff": 5,
                        // Try to get 1 share per this many seconds
                        "targetTime": 15,
                        // Check to see if we should retarget every this many seconds
                        "retargetTime": 10,
                        // Allow time to very this % from target without retargeting
                        "variancePercent": 30,
                        // Do not alter difficulty by more than this during a single retarget in
                        // either direction
                        "maxDelta": 500
                    }
                }
            },
            // Recommended to have at least two daemon instances running in case one drops
            // out-of-sync or offline. For redundancy, all instances will be polled for
            // block/transaction updates and be used for submitting blocks. Creating a backup
            // daemon involves spawning a daemon using the "-datadir=/backup" argument which
            // creates a new daemon instance with it's own RPC config. For more info on this,
            // visit: https:// en.bitcoin.it/wiki/Data_directory and
            // https:// en.bitcoin.it/wiki/Running_bitcoind
            "daemons": [
                {
                    "host": "127.0.0.1",
                    "port": 9053,
                    "user": "user",
                    "password": "pass",
                    "apikey": "apikey",
                    // Enable streaming Block Notifications via ZeroMQ messaging from Bitcoin
                    // Family daemons. Using this is highly recommended. The value of this option
                    // is a string that should match the value of the -zmqpubhashblock parameter
                    // passed to the coin daemon. If you enable this, you should lower
                    // 'blockRefreshInterval' to 1000 or 0 to disable polling entirely.
                    "zmqBlockNotifySocket": "tcp://127.0.0.1:15101",
                    // Enable streaming Block Notifications via WebSocket messaging from Ethereum
                    // family Parity daemons. Using this is highly recommended. The value of this
                    // option is a string that should  match the value of the --ws-port parameter
                    // passed to the parity coin daemon. When using --ws-port, you should also
                    // specify --ws-interface all and
                    // --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc"
                    // If you enable this, you should lower 'blockRefreshInterval' to 1000 or 0
                    // to disable polling entirely.
                    "portWs": 18545,
                }
            ],
            // Generate payouts for recorded shares
            "paymentProcessing": {
                "enabled": true,
                "walletPassword": "pass",
                // Minimum payment in pool-base-currency (ie. Bitcoin, NOT Satoshis)
                "minimumPayment": 0.1,
                "payoutScheme": "PPLNS",
                "payoutSchemeConfig": {
                    "factor": 0.5
                }
            }
        }
        // This section ends here. Add `,` after `}` if this is not the last coin section
    ]
}

**Comment by jvxis** [comment]
I'm also getting this:

[2022-09-03 08:51:48.7785] [D] [ergo1] [0HMKDKAME1UQ7] Dispatching request 'mining.authorize' [2]
[2022-09-03 08:51:48.7814] [I] [ergo1] [0HMKDKAME1UQ7] Authorized worker 9gbwTwZpaTcUb9gcgcV98gnZy8kayULsmXeEbMabPvu2C1MwUSG.rigjvwin
[2022-09-03 08:51:48.7814] [D] [ergo1] [0HMKDKAME1UQ7] Sending: {"result":true,"id":2}
[2022-09-03 08:51:48.7814] [D] [ergo1] [0HMKDKAME1UQ7] Dispatching request 'mining.extranonce.subscribe' [3]
[2022-09-03 08:51:48.7814] [D] [ergo1] [0HMKDKAME1UQ7] Sending: {"jsonrpc":"2.0","method":"mining.set_difficulty","params":[1],"id":null}
[2022-09-03 08:51:48.7814] [D] [ergo1] [0HMKDKAME1UQ7] Unsupported RPC request: {"jsonrpc":"2.0","method":"mining.extranonce.subscribe","params":[],"id":3}
[2022-09-03 08:51:48.7814] [D] [ergo1] [0HMKDKAME1UQ7] Sending: {"jsonrpc":"2.0","method":"mining.notify","params":["00000001",830185,"bc6e5bd95c8507f47d3b9fada844c5581d308495ba9a8c5e3c2e9edfdca119bc","","",2,"28947685835161969569762086241178627721004500325542073861349929123840","",true],"id":null}
[2022-09-03 08:51:48.7814] [D] [ergo1] [0HMKDKAME1UQ7] Sending: {"error":{"code":20,"message":"Unsupported request mining.extranonce.subscribe","data":null},"id":3}
[2022-09-03 08:51:48.7814] [D] [ergo1] [0HMKDKAME1UQ7] [PIPE] Waiting for data ...

I don't know if this error is related with the disconnection problem

**Comment by xmrstickers** [comment]
Please include your OS, mining software, mining software version.

**Comment by jvxis** [comment]
> Please include your OS, mining software, mining software version.

Ubuntu 20.04. Nbminer 42.2 and T-Rex 0.26.5

**Comment by jvxis** [comment]
Closing and opening a discussion thread
