### ISSUE TITLE
Repeated Dag creation process canceled

### ISSUE THREAD

**Issue by yq0810** [oliverw/miningcore#1395]
**Describe the bug**
https://github.com/oliverw/miningcore/blob/05b781046ad1d1a9b35b15e98df1fd96c02f1643/src/Miningcore/Blockchain/Ethereum/EthereumJob.cs#L69

If the Dag is being creating in this line, and the miner keeps disconnecting for some reasons , CancellationToken will cancel the creating progress of Dag, if there is a gap in the Dag generation, pool will be stuck

Should the creating progress of dag not be cancelled by disconnecting worker ?

**Comment by oliverw** [comment]
Thanks for reporting.
