### ISSUE TITLE
Ethereum setDifficulty not working

### ISSUE THREAD

**Issue by yq0810** [oliverw/miningcore#1404]
**Describe the bug**

this way context.ApplyPendingDifficulty() alway false, NotifyAsync SetDifficulty  will never happen.
https://github.com/oliverw/miningcore/blob/8d4073394637a93e22bd39ef04e0cdc3ac45d531/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs#L247

Because the pending has been set to null here with 
https://github.com/oliverw/miningcore/blob/8d4073394637a93e22bd39ef04e0cdc3ac45d531/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs#L536

**Comment by oliverw** [comment]
No correct. This is not the only place where `SendJob` gets called. 

https://github.com/oliverw/miningcore/blob/8d4073394637a93e22bd39ef04e0cdc3ac45d531/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs#L437

**Comment by yq0810** [comment]
https://github.com/oliverw/miningcore/blob/2e3a0f16a4a71b713be0919b49956176bc5fbf05/src/Miningcore/Blockchain/Ethereum/EthereumPool.cs#L530-L549


OnVarDiffUpdateAsync fucntion  called if ApplyPendingDifficulty == true, when the difficulty changes, he will set him to null, but does nothing, and then SendJob can't get ApplyPendingDifficulty == true 

remove it (L530-L549), it works.

**Comment by yq0810** [comment]
This can be fix

https://github.com/oliverw/miningcore/pull/1342/files

**Comment by oliverw** [comment]
I stand corrected. Thanks @yq0810
