### ISSUE TITLE
Ergo: block effort

### ISSUE THREAD

**Issue by jvxis** [oliverw/miningcore#1405]
### Discussed in https://github.com/oliverw/miningcore/discussions/1322

<div type='discussions-op-text'>

<sup>Originally posted by **Censseo** July 22, 2022</sup>
Hello, I'm trying to understand what to do with the block effort, because I don't really understand what the value sent by the api meaning. 
I looked into the code and if I understand well it's the SUM(difficulty/network_difficulty) from shares but the value sent cannot be true because I got something like 0.0033236580321025786, what I am supposed to do with that?</div>

**Comment by oliverw** [comment]
Its very likely that something broke in the last release that fixed some other Ergo problems related to the recent Ergo node update. Currently looking into it.

**Comment by jvxis** [comment]
> Its very likely that something broke in the last release that fixed some other Ergo problems related to the recent Ergo node update. Currently looking into it.

Hi @oliverw I git pull the dev branch. Let's wait for the next block to see if it was fixed. Thanks.

**Comment by oliverw** [comment]
Please update this issue when you got more information.

**Comment by jvxis** [comment]
> Please update this issue when you got more information.

I will. Unfortunately, no blocks so far.

**Comment by oliverw** [comment]
> > Please update this issue when you got more information.
> 
> I will. Unfortunately, no blocks so far.

So?

**Comment by jvxis** [comment]
Nothing yet.

**Comment by ei8ht187** [comment]
> Please update this issue when you got more information.
We've found two blocks. Effort looks good now. Thanks a lot

**Comment by oliverw** [comment]
> > Please update this issue when you got more information.
> > We've found two blocks. Effort looks good now. Thanks a lot

Was this meant to be a quote?

**Comment by ei8ht187** [comment]
Not in that way. Quote your question yes, but not my answer xD.
