### ISSUE TITLE
Error with ETHW mining: ... parsing value: . Path '', line 0, position 0

### ISSUE THREAD

**Issue by Raspimann** [oliverw/miningcore#1467]
i become an error in miningcore time to time ... 

Connection json error: Unexpected character encountered while  parsing value: . Path '', line 0, position 0

behaviour:
the miner software reconnect to the pool after this message is shown and it starts with the start vardiff value ...

thx

**Comment by Raspimann** [comment]
why is this error closed?

**Comment by oliverw** [comment]
It is not a bug.

**Comment by Raspimann** [comment]
is miningcore closed the connection or the miner software? i see that the miner software reconnect to the pool.
