### ISSUE TITLE
Call stats recorder asynchronously 

### ISSUE THREAD

**Issue by jon4hz** [oliverw/miningcore#1472]
From what I can tell miningcore collects the stats from each pool sequentially.

Do you think it would make sense to call `UpdatePoolHashratesAsync` for each individual pool and await them using `Task.WhenAll()`? 

https://github.com/oliverw/miningcore/blob/2311784f0eb5e5f6180a5ac12eec2c9a270f9ca5/src/Miningcore/Mining/StatsRecorder.cs#L100

**Comment by oliverw** [comment]
The current implementation is sequential to avoid load spikes on MC itself and on the database (which would probably take the brunt of the load). May I ask what the motivation for the question is?

**Comment by jon4hz** [comment]
Recently we started having some issues with the stats collection when the shares table started to grow for a single pool. 
Since the stats collection is sequentially, that one pool slows down all the others. 

The weird thing is that neither miningcore itself nor the database hit any resource limits.

Calling the stats collection asynchronously was just an idea how we could improve the performance at least a bit. Obviously the collector would still be just as fast as the slowest pool.

**Comment by oliverw** [comment]
> Recently we started having some issues with the stats collection when the shares table started to grow for a single pool. Since the stats collection is sequentially, that one pool slows down all the others.
> 
> The weird thing is that neither miningcore itself nor the database hit any resource limits.
> 
> Calling the stats collection asynchronously was just an idea how we could improve the performance at least a bit. Obviously the collector would still be just as fast as the slowest pool.

I'd say go for it and perform some testing.
