### ISSUE TITLE
Error installing ubuntu 22.04 with script

### ISSUE THREAD

**Issue by edcomrocha** [oliverw/miningcore#1473]
Hello.
I'm trying to install MiningCore on ubuntu 22.04.1.
Using installation script and it never completes.
I tried manually too, but I always get the same error:

`/home/edvaldo/miningcore/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: The command "(cd /home/edvaldo/miningcore/src/Miningcore/ && sh build-libs-linux.sh bin/ Release/net6.0/)" exited with code -1.
`

I looked for an old way that we had to install but I couldn't find it anymore.
``
Any light on something I might be doing wrong?

I'm installing on an exsi vmware

>

**Comment by coin-pool** [comment]
you install it on VM ? if yes, the hypervisor is proxmox  or vmware ?

**Comment by edcomrocha** [comment]
> you install it on VM ? if yes, the hypervisor is proxmox or vmware ?

Hi thanks for replying.

Installing on Vmware, ESXI.

I also tried to run on windows on my machine without virtualization but I got the same error.

**Comment by fer000n** [comment]
solved? have same problem ubuntu 20.04

**Comment by edcomrocha** [comment]
> solved? have same problem ubuntu 20.04

I did not make it.
I tried on other versions of ubuntu and on windows and it keeps the same error

**Comment by xyrox54** [comment]
I have the same problem and I can't find the solution. I think it's an error related to the NET6 SDK.

**Comment by j2ckson** [comment]
I had the same problem and fixed go around it as follows:

Run the install script until it fails.
cd ./src/Miningcore
cp ./bin/Release/net6.0/librandomarq.so ./
sh build-libs-linux.sh bin/Release/net6.0/

**Comment by edcomrocha** [comment]
> I had the same problem and fixed it as follows:
> 
> Run the install script until it fails. cd ./src/Miningcore cp ./bin/Release/net6.0/librandomarq.so ./ sh build-libs-linux.sh bin/Release/net6.0/

Hello.
Thank you for your help.

I'll test it as soon as I have free time and report back here.

hug

**Comment by says112** [comment]
Please specify how you fixed it I have the same problem?
![Снимок экрана (302)](https://user-images.githubusercontent.com/22127398/200196694-67601a01-8f70-4303-a71a-32d3360c1eaa.png)

**Comment by says112** [comment]
What kind of mistake is this?
![Снимок экрана (305)](https://user-images.githubusercontent.com/22127398/200333904-75820268-78b3-4b34-8b9d-d69809cdc9a4.png)

**Comment by fer000n** [comment]
> > I had the same problem and fixed it as follows:
> > 
> > Run the install script until it fails. cd ./src/Miningcore cp ./bin/Release/net6.0/librandomarq.so ./ sh build-libs-linux.sh bin/Release/net6.0/
> 
> Hello.
> Thank you for your help.
> 
> I'll test it as soon as I have free time and report back here.
> 
> hug

Hi, did it worked?

**Comment by says112** [comment]
> У меня была та же проблема, и я исправил ее следующим образом:
> 
> Запускайте сценарий установки до тех пор, пока он не завершится ошибкой. cd ./src/Miningcorecp ./bin/Release/net6.0/librandomarq.so ./sh build-libs-linux.sh bin/Release/net6.0/

Not going to no BUILD folder after build.

**Comment by fer000n** [comment]
> I had the same problem and fixed it as follows:
> 
> Run the install script until it fails. cd ./src/Miningcore cp ./bin/Release/net6.0/librandomarq.so ./ sh build-libs-linux.sh bin/Release/net6.0/

cp: cannot stat './bin/Release/net6.0/librandomarq.so': No such file or directory
Not wroking

**Comment by edcomrocha** [comment]
> > > Tive o mesmo problema e resolvi da seguinte forma:
> > > Execute o script de instalação até que ele falhe. cd ./src/Miningcore cp ./bin/Release/net6.0/librandomarq.so ./ sh build-libs-linux.sh bin/Release/net6.0/
> > 
> > 
> > Olá. 
> > Obrigado pela ajuda.
> > Vou testar assim que tiver tempo livre e volto aqui para contar.
> > abraço
> 
> Olá, funcionou?

Hello. Sorry, I'm on a trip and I still can't test it.

I'll be back next week, as soon as I get back I'll be able to test it

**Comment by btclinux** [comment]
Try to just comment out last four strings here https://github.com/oliverw/miningcore/blob/2311784f0eb5e5f6180a5ac12eec2c9a270f9ca5/src/Miningcore/build-libs-linux.sh#L27 related to cryptonotes

**Comment by fer000n** [comment]
this fork works fine 
https://github.com/lurchinms/miningcore_kriptokyng

**Comment by minershaven** [comment]
Had issues with this a while back. Check and see if everything gets built to the 
/Miningcore/bin/Release/net6.0 folder and if so just copy everything in there to the build folder and everything will work fine.  I used that as a temp fix until I was able to get it to build correctly. If I remember correctly there was some kind of ownership or permissions issue that prevented it from either accessing or writing to one of the folders.  If that doesn't work you can try my version out and see if it builds for you.

**Comment by n128au** [comment]
I have the same problem on ubuntu 20.04 i tried following the tips but no solution found

**Comment by edcomrocha** [comment]
> this fork works fine https://github.com/lurchinms/miningcore_kriptokyng

I did several tests.

Only this one worked for me.
