### ISSUE TITLE
[litecoin] Daemon has downloaded 100.00% of blockchain from 10 peers 

### ISSUE THREAD

**Issue by idanzam** [oliverw/miningcore#1503]
**Describe the bug**
[litecoin] Daemon has downloaded 100.00% of blockchain from 10 peers 

coin.json: 

 "litecoin": {
        "name": "Litecoin",
        "canonicalName": "Litecoin",
        "symbol": "LTC",
        "family": "bitcoin",
        "website": "",
        "market": "",
        "twitter": "",
        "telegram": "",
        "discord": "",
        "coinbaseHasher": {
            "hash": "sha256d"
        },
        "headerHasher": {
            "hash": "scrypt",
            "args": [ 1024, 1 ]
        },
        "blockHasher": {
            "hash": "reverse",
            "args": [ { "hash": "sha256d" } ]
        },
        "posBlockHasher": {
            "hash": "reverse",
            "args": [
                {
                    "hash": "scrypt",
                    "args": [ 1024, 1 ]
                }
            ]
        },

        "shareMultiplier": 65536,
        "explorerBlockLink": "https://chainz.cryptoid.info/ltc/block.dws?$height$.htm",
        "explorerTxLink": "https://chainz.cryptoid.info/ltc/tx.dws?{0}.htm",
        "explorerAccountLink": "https://chainz.cryptoid.info/ltc/address.dws?{0}.htm",

 - OS: ubuntu 22.04 LTS

wallet conf file:

rpcuser=****
rpcpassword=****
rpcport=17501
host=127.0.0.1
listen=0
daemon=1
maxconnections=50
rpcthreads=8
gen=0

any solution ? what do I miss?

**Comment by seperatis** [comment]
@idanzam Um, it appears your `coin.json` is missing a bunch of stuff. It should look similar to this one
 --> https://github.com/oliverw/miningcore/blob/master/examples/litecoin_pool.json

This is not a BUG, but a user misconfiguration. Please, everyone....**do not open issues** unless you find something in the software **code** that is not working as intended. For everything else, please search the WIKI, old issues, and if you can't find answers that way, then [start a discussion](https://github.com/oliverw/miningcore/discussions). 

I am closing b/c this is not a bug.

**Comment by jon4hz** [comment]
Actually this is a bug :) 

Miningcore fails to fetch the initial blocktemplate due to the mweb changes. It's miningcore who reports it poorly. #1563 should fix this issue.
