### ISSUE TITLE
Uncorrected work of asics with the miningcore pool.

### ISSUE THREAD

**Issue by says112** [oliverw/miningcore#1515]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Hello! I collected my pool on sha256, but the problem is that the hashrate of asics ebit decreases by half after a few hours of work.After the reboot, everything is fine, then a few hours later the same thing.Everything is fine on other pools. What could be the problem?

**Comment by oliverw** [comment]
Is vardiff enabled?

**Comment by says112** [comment]
In the settings?

**Comment by oliverw** [comment]
> In the settings?

Both in Miningcore's configuration file and/or the miner. It's generally advisable to run ASICs with static diff using `D=x` as password to request Miningcore to disable vardiff. `x` denotes a difficulty you manually have to figure out by tuning it by hand that results in a steady stream of shares of one every few seconds.

**Comment by says112** [comment]
I wonder how to do it?

**Comment by oliverw** [comment]
> I wonder how to do it?

I've explained it above.

**Comment by says112** [comment]
![Uploading Снимок экрана (402).png…]()
The complexity of 4.8 g is indicated here

**Comment by says112** [comment]
![Снимок экрана (402)](https://user-images.githubusercontent.com/22127398/204102168-a8aa0d14-5d45-4953-a222-aef1a4b30a98.png)

The complexity of 4.8 g is indicated here

**Comment by says112** [comment]
So you need to specify 4800 in the password?

**Comment by says112** [comment]
For some reason, it incorrectly shows the hashrate of the network.
