### ISSUE TITLE
ERROR:  relation "shares" does not exist

### ISSUE THREAD

**Issue by MCrissDev** [oliverw/miningcore#1531]
**ERROR:  relation "shares" does not exist**

**To Reproduce**
psql (15.1 (Debian 15.1-1.pgdg110+1), server 13.8 (Debian 13.8-0+deb11u1))

sudo -u postgres psql
CREATE TABLE shares_mypool PARTITION OF shares FOR VALUES IN ('radiant_mypool');

ERROR:  relation "shares" does not exist

--When running--
processed: 0 items - remaining: 1 items 
[2022-12-03 11:56:37.8203] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (23514: no partition of relation "shares" found for row

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.) 

**Expected behavior**
No error should occur

**Comment by oliverw** [comment]
This is not a bug. Read the instructions.

**Comment by MCrissDev** [comment]
I've read the instructions and applied them step by step (2 different times actually) but the error still occurred. Did I miss something? Thank you,
