### ISSUE TITLE
StratumShare record

### ISSUE THREAD

**Issue by jon4hz** [oliverw/miningcore#1536]
Hey, 

Is the `Connection` parameter required here?
https://github.com/oliverw/miningcore/blob/171a262a3f7861bbb54178d385806b9afebcb0af/src/Miningcore/Mining/StratumShare.cs#L6

From what I can see, this field is accessed nowhere else.

**Comment by oliverw** [comment]
There used to be listeners on the message bus that cared for the `Connection` member but those are long gone since the vardiff rework. I'll remove it. Thanks for the advice.
