### ISSUE TITLE
bitcoin gold algo equihash 144,5 [zhash] not working 

### ISSUE THREAD

**Issue by goodthebest** [oliverw/miningcore#1538]
Miningcore isn't working with bitcoin gold even though it's in the list of functional coins. I've tested the pool with nicehash and it's not compatible, @oliverw any thoughts?

**Comment by oliverw** [comment]
Just because Nicehash is acting up (as usual), does not mean BTG is not working in Miningcore. Please don't make such broad statements.

https://miningcore.pro/pool/btg

**Comment by goodthebest** [comment]
That's interesting, could you please share btg config.json?

**Comment by oliverw** [comment]
> That's interesting, could you please share btg config.json?

There's absolutely nothing special about the configuration for BTG.

**Comment by minershaven** [comment]
Works fine on my pool also. It's was the first coin I added.

**Comment by Konstantin35** [comment]
> Miningcore isn't working with bitcoin gold even though it's in the list of functional coins. I've tested the pool with nicehash and it's not compatible, @oliverw any thoughts?

To make it work properly, you need to refine it according to the specifications  
https://github.com/nicehash/Specifications/blob/master/Zhash_NiceHash_v1.0.txt

**Comment by Konstantin35** [comment]
It looks like this if you have time to add 
```
jobParams = new object[]
{
    JobId,
    BlockTemplate.Version.ReverseByteOrder().ToStringHex8(),
    previousBlockHashReversedHex,
    merkleRootReversedHex,
    BlockTemplate.Height.ReverseByteOrder().ToStringHex8() + sha256Empty.Take(28).ToHexString(), // height + hashReserved
    BlockTemplate.CurTime.ReverseByteOrder().ToStringHex8(),
    BlockTemplate.Bits.HexToReverseByteArray().ToHexString(),
    false,
    "144_5",
    "BgoldPoW",
};
```

here it is better to determine which coin
```
    public object GetJobParams(bool isNew)
    {
        jobParams[^3] = isNew;
        return jobParams;
    }
```

**Comment by goodthebest** [comment]
@Konstantin35 in which file I need to add those lines?

**Comment by Konstantin35** [comment]
> @Konstantin35 in which file I need to add those lines?

If you don’t know where it is, I think you shouldn’t make a mistake, then the above is not all required in `OnSubscribeAsync` `error` and should be removed from `OnAuthorizeAsync` `CancellationToken` and replaced in `ValidateAddressAsync` with `CancellationToken.None`
