### ISSUE TITLE
The example files do not work.

### ISSUE THREAD

**Issue by bmilanov1** [oliverw/miningcore#1555]
running the following
 ./Miningcore -c ../examples/zcash_pool.json

getting the following
Using configuration file '../examples/zcash_pool.json'
Configuration file error: Value "integrated" is not defined in enum. Path 'banning.manager', line 11, position 31.

At the reported position I replaced the small letter i with capital I and then got another error:
Configuration file error: Could not convert string 'daemons' to dictionary key type 'System.Int32'. Create a TypeConverter to convert from the string to the key type object. Path 'pools[0].ports.daemons', line 78, position 16.

Is there anyone able to run this out of the installer without any errors?

**Comment by seperatis** [comment]
@bmilanov1 After referencing https://github.com/oliverw/miningcore/wiki/Configuration 
I see that in the example config it is "Integrated" not "integrated". Perhaps give that a try.

**Comment by bmilanov1** [comment]
As I mentioned in my previous post this got resolved the way you mentioned. However, there is another error:
Configuration file error: Could not convert string 'daemons' to dictionary key type 'System.Int32'. Create a TypeConverter to convert from the string to the key type object. Path 'pools[0].ports.daemons', line 78, position 16.

**Comment by bmilanov1** [comment]
Thanks for the help. You were correct. There was a missing }
