### ISSUE TITLE
install 22.04 error dotnet-sdk -6

### ISSUE THREAD

**Issue by david739** [oliverw/miningcore#1564]
hi, I'm trying to install it on 22.04 ubuntu but it doesn't work with 6, with 7 the installation starts and completes but it requires 6 to run miningcore. can you please advise me or please rebuild it to dotnet-sdk -7

**Comment by oliverw** [comment]
I cannot reproduce this.

**Comment by neil-mando** [comment]
I guess that you were trying to build using script.
> ./build-ubuntu-22.04.sh

then you might found errors like.
> Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.json/index.json'.                                     
> Resource temporarily unavailable (api.nuget.org:443)                                                                                                                         
>    Resource temporarily unavailable                                                                                                                                           
> Failed to download package 'FluentValidation.11.2.2' from 'https://api.nuget.org/v3-flatcontainer/fluentvalidation/11.2.2/fluentvalidation.11.2.2.nupkg'.       

In my case adding **--disable-parallel** can solve this issue both on the script and Dockerfile.

On script this line 
`dotnet publish -c Release --framework net6.0 -o $BUILDIR)`
add --disable-parallel
`dotnet publish -c Release --disable-parallel --framework net6.0 -o $BUILDIR)`

On Dockerfile this line
`RUN dotnet publish -c Release --framework net6.0 -o ../../build`
add --disable-parallel
`RUN dotnet publish -c Release --disable-parallel --framework net6.0 -o ../../build`

**Comment by david739** [comment]
hi, thanks for the tip, I'll try it right away, so far I'm limited to ubuntu 20.04

**Comment by david739** [comment]
Hi, the procedure works, thank you

**Comment by david739** [comment]
hello, I have only 1 problem, everything is ok, I just can't import sql, no problem with 20.04, but with 22.04 it says access denied, the path is correct

sudo -u postgres psql -d miningcore -f /home/xxx/miningcore/src/Miningcore/Persistence/Postgres/Scripts/createdb.sql
