### ISSUE TITLE
MacOS docker build failure

### ISSUE THREAD

**Issue by xmr-dev** [oliverw/miningcore#1584]
I followed the instruction on the README for docker MacOS. The following command causes an error:
`docker run --rm -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/sdk:6.0 /bin/bash -c 'apt update && apt install libssl-dev pkg-config libboost-all-dev libsodium-dev build-essential cmake -y --no-install-recommends && cd src/Miningcore && dotnet publish -c Release --framework net6.0 -o /app/build/ -r osx-x64 --self-contained false'
` 

The error:
`/app/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: The command "(cd /app/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/osx-x64/)" exited with code -1.`

Docker version:
`Docker version 20.10.22, build 3a2c30b`

Mac version: 
`13.1 (Ventura)`

**Steps to reproduce**
1) enter the following command in terminal with the versions mentioned above. 
`docker run --rm -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/sdk:6.0 /bin/bash -c 'apt update && apt install libssl-dev pkg-config libboost-all-dev libsodium-dev build-essential cmake -y --no-install-recommends && cd src/Miningcore && dotnet publish -c Release --framework net6.0 -o /app/build/ -r osx-x64 --self-contained false'
` 

**Expected behavior**
The program compiles

**Screenshots**
<img width="1440" alt="Screenshot 2023-01-14 at 11 11 13" src="https://user-images.githubusercontent.com/73394958/212466951-c7581907-71ca-449b-a70b-597b80fba594.png">

**Comment by djjenova** [comment]
I got the same issue as well on macOS Monterey 12.5.1, Docker version 20.10.21

**Comment by oliverw** [comment]
Sorry, Miningcore never supported macOS. This is not some arbitrary restriction by the way. MC utilizes a lot of native code (the stuff in `src/Native`) which is currently not compiling under macOS.

**Comment by xmr-dev** [comment]
@oliverw too bad, maybe update the readme?
