### ISSUE TITLE
config.json adding more than one coin isn't working

### ISSUE THREAD

**Issue by goodthebest** [oliverw/miningcore#1588]
I've added two coins in config.json first is BTC and other is Litecoincash, however miningcore is only picking up first coin that is BTC while ignoring Litecoincash.  And there is no error for second coin that is litecoincash.

**Comment by idanzam** [comment]
your "id": "BTC",
is wrong bro
the ID must be same as coin.json:

 **"bitcoin": {**
        "name": "Bitcoin",
        "canonicalName": "Bitcoin",
        "symbol": "BTC",.........


so your "id":"bitcoin" - the header of the array.

change it and u will see all ok.

you have also duplicate things . needed 1 loggin, 1 api, and so on until Pools section.

and last thing all address must be LEGACY.

**Comment by goodthebest** [comment]
@idanzam thanks bro, got it.

**Comment by ghost** [comment]
The ID can be anything. "coin" must match the id in coins.json.

So the header is correct:
"pools": [
	{
      "id": "BTC",   --> Anything you wants
      "enabled": true,
      "coin": "bitcoin",    ->>  from coins.json 

If you run more than one coin, create a cluster before "pools". e.g: 

 "clusterName": "eu1",         --> Anithing you want
    "pools": [
	{
      "id": "gold",
      "enabled": true,
      "coin": "goldcash",
       ....
      },             
      {
      "id": "BTC",
      "enabled": true,
      "coin": "bitcoin"
      .....
      }
