### ISSUE TITLE
Xolentum

### ISSUE THREAD

**Issue by swa74** [oliverw/miningcore#972]
I am trying to add a coin Xolentum (randomx).
The pool starts, but xmrig writes login error code 2
"xolentum": {
"name": "Xolentum",
"symbol": "XOL",
"family": "cryptonote",
"hash": "randomx",
"hashVariant": 0,
smallestUnit: 1000000000000,
"addressPrefix": 185,
"addressPrefixStagenet": 20152,
"addressPrefixTestnet": 23480,
"addressPrefixIntegrated": 251,
"addressPrefixIntegratedStagenet": 9210,
"addressPrefixIntegratedTestnet": 12666,
"explorerBlockLink": "https://explorer.xolentum.org/?hash= {id }#blockchain_block",
"explorerTxLink": "https://explorer.xolentum.org/?hash= {id }#blockchain_transaction"
},
What's my mistake ? xmr connects and accepts balls

**Comment by oliverw** [comment]
Update on this?
