### ISSUE TITLE
Timestamp on API is not correct

### ISSUE THREAD

**Issue by riksarchen** [oliverw/miningcore#984]
Generally the timestamps on the API is wrong. It's supposed to be in UTC but it's missing "Z" at the end. 

created: "2021-10-30T20:03:48.557948"

Correct should be:
created: "2021-10-30T20:03:48.557948Z"

**Comment by oliverw** [comment]
So the actually value is correct but it is just not designated to be UTC?

**Comment by riksarchen** [comment]
Correct. All entries is correct in UTC. It's just lacking the Z at the end telling js the timedtamp is in UTC. It's correct for lastNetworkBlockTime under api/pools/id 
But that's the only one that seems correct.

**Comment by oliverw** [comment]
Please re-test with v65.

**Comment by riksarchen** [comment]
V66 was already released when I saw this message. I tried it in V66 and it seems to be working :-)
